var je_present = [ "aime", "arrête", "bavarde", "cache", "cherche", "danse", "donne", "entre", "ferme", "grimpe", "habite", "invente", "joue", "lave", "monte", "oublie", "parle", "raconte", "regarde", "salue", "siffle", "téléphone", "tire", "vole", "commence", "mange", "nage", "lance", "cueille", "ouvre", "couvre", "offre", "souffre", "mène", "lève", "me lève", "jette", "répète", "espère", "envoie", "achète", "enlève", "pèse", "promène", "me promène", "appelle", "m'appelle", "épelle", "exagère", "inquiète", "protège", "sèche", "ennuie", "nettoie", "essaie", "paie", "essuie", "applaudis", "atterris", "choisis", "finis", "maigris", "obéis", "punis", "remplis", "rôtis", "garantis", "grandis", "grossis", "jaunis", "réfléchis", "réussis", "rougis", "vieillis", "meurs", "cours", "viens", "tiens", "dors", "pars", "sors", "mens", "sens", "sers", "fuis", "m'enfuis", "attends", "défends", "descends", "entends", "perds", "rends", "réponds", "vends", "romps", "crains", "plains", "peins", "éteins", "atteins", "conduis", "construis", "traduis", "produis", "connais", "parais", "nais", "plais", "me tais", "prends", "mets", "bats", "lis", "bois", "vis", "crois", "ris", "suis", "suffis", "fais", "dis", "écris", "reçois", "déçois", "aperçois", "dois", "peux", "veux", "faut", "vaux", "m'assieds", "sais", "vois", "pleut" ];
var tu_present = [ "aimes", "arrêtes", "bavardes", "caches", "cherches", "danses", "donnes", "entres", "fermes", "grimpes", "habites", "inventes", "joues", "laves", "montes", "oublies", "parles", "racontes", "regardes", "salues", "siffles", "téléphones", "tires", "voles", "commences", "manges", "nages", "lances", "cueilles", "ouvres", "couvres", "offres", "souffres", "mènes", "lèves", "te lèves", "jettes", "répètes", "espères", "envoies", "achètes", "enlèves", "pèses", "promènes", "te promènes", "appelles", "t'appelles", "épelles", "exagères", "inquiètes", "protèges", "sèches", "ennuies", "nettoies", "essaies", "paies", "essuies", "applaudis", "atterris", "choisis", "finis", "maigris", "obéis", "punis", "remplis", "rôtis", "garantis", "grandis", "grossis", "jaunis", "réfléchis", "réussis", "rougis", "vieillis", "meurs", "cours", "viens", "tiens", "dors", "pars", "sors", "mens", "sens", "sers", "fuis", "t'enfuis", "attends", "défends", "descends", "entends", "perds", "rends", "réponds", "vends", "romps", "crains", "plains", "peins", "éteins", "atteins", "conduis", "construis", "traduis", "produis", "connais", "parais", "nais", "plais", "te tais", "prends", "mets", "bats", "lis", "bois", "vis", "crois", "ris", "suis", "suffis", "fais", "dis", "écris", "reçois", "déçois", "aperçois", "dois", "peux", "veux", "faut", "vaux", "t'assieds", "sais", "vois", "pleut" ];
var il_present = [ "aime", "arrête", "bavarde", "cache", "cherche", "danse", "donne", "entre", "ferme", "grimpe", "habite", "invente", "joue", "lave", "monte", "oublie", "parle", "raconte", "regarde", "salue", "siffle", "téléphone", "tire", "vole", "commence", "mange", "nage", "lance", "cueille", "ouvre", "couvre", "offre", "souffre", "mène", "lève", "se lève", "jette", "répète", "espère", "envoie", "achète", "enlève", "pèse", "promène", "se promène", "appelle", "s'appelle", "épelle", "exagère", "inquiète", "protège", "sèche", "ennuie", "nettoie", "essaie", "paie", "essuie", "applaudit", "atterrit", "choisit", "finit", "maigrit", "obéit", "punit", "remplit", "rôtit", "garantit", "grandit", "grossit", "jaunit", "réfléchit", "réussit", "rougit", "vieillit", "meurt", "court", "vient", "tient", "dort", "part", "sort", "ment", "sent", "sert", "fuit", "s'enfuit", "attend", "défend", "descend", "entend", "perd", "rend", "répond", "vend", "rompt", "craint", "plaint", "peint", "éteint", "atteint", "conduit", "construit", "traduit", "produit", "connaît", "paraît", "naît", "plaît", "se tait", "prend", "met", "bat", "lit", "boit", "vit", "croit", "rit", "suit", "suffit", "fait", "dit", "écrit", "reçoit", "déçoit", "aperçoit", "doit", "peut", "veut", "faut", "vaut", "s'assied", "sait", "voit", "pleut" ];
var nous_present = [ "aimons", "arrêtons", "bavardons", "cachons", "cherchons", "dansons", "donnons", "entrons", "fermons", "grimpons", "habitons", "inventons", "jouons", "lavons", "montons", "oublions", "parlons", "racontons", "regardons", "saluons", "sifflons", "téléphonons", "tirons", "volons", "commençons", "mangeons", "nageons", "lançons", "cueillons", "ouvrons", "couvrons", "offrons", "souffrons", "menons", "levons", "nous levons", "jetons", "répétons", "espérons", "envoyons", "achetons", "enlevons", "pesons", "promenons", "nous promenons", "appelons", "nous appelons", "épelons", "exagérons", "inquiétons", "protégeons", "séchons", "ennuyons", "nettoyons", "essayons", "payons", "essuyons", "applaudissons", "atterrissons", "choisissons", "finissons", "maigrissons", "obéissons", "punissons", "remplissons", "rôtissons", "garantissons", "grandissons", "grossissons", "jaunissons", "réfléchissons", "réussissons", "rougissons", "vieillissons", "mourons", "courons", "venons", "tenons", "dormons", "partons", "sortons", "mentons", "sentons", "servons", "fuyons", "nous enfuyons", "attendons", "défendons", "descendons", "entendons", "perdons", "rendons", "répondons", "vendons", "rompons", "craignons", "plaignons", "peignons", "éteignons", "atteignons", "conduisons", "construisons", "traduisons", "produisons", "connaissons", "paraissons", "naissons", "plaisons", "nous taisons", "prenons", "mettons", "battons", "lisons", "buvons", "vivons", "croyons", "rions", "suivons", "suffisons", "faisons", "disons", "écrivons", "recevons", "décevons", "apercevons", "devons", "pouvons", "voulons", "fallons", "valons", "nous asseyons", "savons", "voyons", "pleuvons" ];
var vous_present = [ "aimez", "arrêtez", "bavardez", "cachez", "cherchez", "dansez", "donnez", "entrez", "fermez", "grimpez", "habitez", "inventez", "jouez", "lavez", "montez", "oubliez", "parlez", "racontez", "regardez", "saluez", "sifflez", "téléphonez", "tirez", "volez", "commencez", "mangez", "nagez", "lancez", "cueillez", "ouvrez", "couvrez", "offrez", "souffrez", "menez", "levez", "vous levez", "jetez", "répétez", "espérez", "envoyez", "achetez", "enlevez", "pesez", "promenez", "vous promenez", "appelez", "vous appelez", "épelez", "exagérez", "inquiétez", "protégez", "séchez", "ennuyez", "nettoyez", "essayez", "payez", "essuyez", "applaudissez", "atterrissez", "choisissez", "finissez", "maigrissez", "obéissez", "punissez", "remplissez", "rôtissez", "garantissez", "grandissez", "grossissez", "jaunissez", "réfléchissez", "réussissez", "rougissez", "vieillissez", "mourez", "courez", "venez", "tenez", "dormez", "partez", "sortez", "mentez", "sentez", "servez", "fuyez", "vous enfuyez", "attendez", "défendez", "descendez", "entendez", "perdez", "rendez", "répondez", "vendez", "rompez", "craignez", "plaignez", "peignez", "éteignez", "atteignez", "conduisez", "construisez", "traduisez", "produisez", "connaissez", "paraissez", "naissez", "plaisez", "vous taisez", "prenez", "mettez", "battez", "lisez", "buvez", "vivez", "croyez", "riez", "suivez", "suffisez", "faites", "dites", "écrivez", "recevez", "décevez", "apercevez", "devez", "pouvez", "voulez", "fallez", "valez", "vous asseyez", "savez", "voyez", "pleuvez" ];
var ils_present = [ "aiment", "arrêtent", "bavardent", "cachent", "cherchent", "dansent", "donnent", "entrent", "ferment", "grimpent", "habitent", "inventent", "jouent", "lavent", "montent", "oublient", "parlent", "racontent", "regardent", "saluent", "sifflent", "téléphonent", "tirent", "volent", "commencent", "mangent", "nagent", "lancent", "cueillent", "ouvrent", "couvrent", "offrent", "souffrent", "mènent", "lèvent", "se lèvent", "jettent", "répètent", "espèrent", "envoient", "achètent", "enlèvent", "pèsent", "promènent", "se promènent", "appellent", "s'appellent", "épellent", "exagèrent", "inquiètent", "protègent", "sèchent", "ennuient", "nettoient", "essaient", "paient", "essuient", "applaudissent", "atterrissent", "choisissent", "finissent", "maigrissent", "obéissent", "punissent", "remplissent", "rôtissent", "garantissent", "grandissent", "grossissent", "jaunissent", "réfléchissent", "réussissent", "rougissent", "vieillissent", "meurent", "courent", "viennent", "tiennent", "dorment", "partent", "sortent", "mentent", "sentent", "servent", "fuient", "s'enfuient", "attendent", "défendent", "descendent", "entendent", "perdent", "rendent", "répondent", "vendent", "rompent", "craignent", "plaignent", "peignent", "éteignent", "atteignent", "conduisent", "construisent", "traduisent", "produisent", "connaissent", "paraissent", "naissent", "plaisent", "se taisent", "prennent", "mettent", "battent", "lisent", "boivent", "vivent", "croient", "rient", "suivent", "suffisent", "font", "disent", "écrivent", "reçoivent", "déçoivent", "aperçoivent", "doivent", "peuvent", "veulent", "fallent", "valent", "s'asseyent", "savent", "voient", "pleuvent" ];

var je_passe_compose = [ "ai aimé", "ai arrêté", "ai bavardé", "ai caché", "ai cherché", "ai dansé", "ai donné", "suis entré", "ai fermé", "ai grimpé", "ai habité", "ai inventé", "ai joué", "ai lavé", "suis monté", "ai oublié", "ai parlé", "ai raconté", "ai regardé", "ai salué", "ai sifflé", "ai téléphoné", "ai tiré", "ai volé", "ai commencé", "ai mangé", "ai nagé", "ai lancé", "ai cueilli", "ai ouvert", "ai couvert", "ai offert", "ai souffert", "ai mené", "ai levé", "me suis levé", "ai jeté", "ai répété", "ai espéré", "ai envoyé", "ai acheté", "ai enlevé", "ai pesé", "ai promené", "me suis promené", "ai appelé", "m'ai appelé", "ai épelé", "ai exagéré", "ai inquiété", "ai protégé", "ai séché", "ai ennuyé", "ai nettoyé", "ai essayé", "ai payé", "ai essuyé", "ai applaudi", "ai atterri", "ai choisi", "ai fini", "ai maigri", "ai obéi", "ai puni", "ai rempli", "ai rôti", "ai garanti", "ai grandi", "ai grossi", "ai jauni", "ai réfléchi", "ai réussi", "ai rougi", "ai vieilli", "suis mort", "ai couru", "suis venu", "ai tenu", "ai dormi", "suis parti", "suis sorti", "ai menti", "ai senti", "ai servi", "ai fui", "me suis enfui", "ai attendu", "ai défendu", "suis descendu", "ai entendu", "ai perdu", "ai rendu", "ai répondu", "ai vendu", "ai rompu", "ai craint", "ai plaint", "ai peint", "ai éteint", "ai atteint", "ai conduit", "ai construit", "ai traduit", "ai produit", "ai connu", "ai paru", "suis né", "ai plu", "me suis tu", "ai pris", "ai mis", "ai battu", "ai lu", "ai bu", "ai vécu", "ai cru", "ai ri", "ai suivi", "ai suffi", "ai fait", "ai dit", "ai écrit", "ai reçu", "ai déçu", "ai aperçu", "ai dû", "ai pu", "ai voulu", "a fallu", "ai valu", "me suis assis", "ai su", "ai vu", "a plu" ];
var tu_passe_compose = [ "as aimé", "as arrêté", "as bavardé", "as caché", "as cherché", "as dansé", "as donné", "es entré", "as fermé", "as grimpé", "as habité", "as inventé", "as joué", "as lavé", "es monté", "as oublié", "as parlé", "as raconté", "as regardé", "as salué", "as sifflé", "as téléphoné", "as tiré", "as volé", "as commencé", "as mangé", "as nagé", "as lancé", "as cueilli", "as ouvert", "as couvert", "as offert", "as souffert", "as mené", "as levé", "t'es levé", "as jeté", "as répété", "as espéré", "as envoyé", "as acheté", "as enlevé", "as pesé", "as promené", "t'es promené", "as appelé", "t'as appelé", "as épelé", "as exagéré", "as inquiété", "as protégé", "as séché", "as ennuyé", "as nettoyé", "as essayé", "as payé", "as essuyé", "as applaudi", "as atterri", "as choisi", "as fini", "as maigri", "as obéi", "as puni", "as rempli", "as rôti", "as garanti", "as grandi", "as grossi", "as jauni", "as réfléchi", "as réussi", "as rougi", "as vieilli", "es mort", "as couru", "es venu", "as tenu", "as dormi", "es parti", "es sorti", "as menti", "as senti", "as servi", "as fui", "t'es enfui", "as attendu", "as défendu", "es descendu", "as entendu", "as perdu", "as rendu", "as répondu", "as vendu", "as rompu", "as craint", "as plaint", "as peint", "as éteint", "as atteint", "as conduit", "as construit", "as traduit", "as produit", "as connu", "as paru", "es né", "as plu", "t'es tu", "as pris", "as mis", "as battu", "as lu", "as bu", "as vécu", "as cru", "as ri", "as suivi", "as suffi", "as fait", "as dit", "as écrit", "as reçu", "as déçu", "as aperçu", "as dû", "as pu", "as voulu", "a fallu", "as valu", "t'es assis", "as su", "as vu", "a plu" ];
var il_passe_compose = [ "a aimé", "a arrêté", "a bavardé", "a caché", "a cherché", "a dansé", "a donné", "est entré", "a fermé", "a grimpé", "a habité", "a inventé", "a joué", "a lavé", "est monté", "a oublié", "a parlé", "a raconté", "a regardé", "a salué", "a sifflé", "a téléphoné", "a tiré", "a volé", "a commencé", "a mangé", "a nagé", "a lancé", "a cueilli", "a ouvert", "a couvert", "a offert", "a souffert", "a mené", "a levé", "s'est levé", "a jeté", "a répété", "a espéré", "a envoyé", "a acheté", "a enlevé", "a pesé", "a promené", "s'est promené", "a appelé", "s'a appelé", "a épelé", "a exagéré", "a inquiété", "a protégé", "a séché", "a ennuyé", "a nettoyé", "a essayé", "a payé", "a essuyé", "a applaudi", "a atterrit", "a choisi", "a fini", "a maigri", "a obéit", "a puni", "a rempli", "a rôti", "a garanti", "a grandi", "a grossi", "a jauni", "a réfléchi", "a réussi", "a rougi", "a vieilli", "est mort", "a couru", "est venu", "a tenu", "a dormi", "est parti", "est sorti", "a menti", "a senti", "a servi", "a fui", "s'est enfui", "a attendu", "a défendu", "est descendu", "a entendu", "a perdu", "a rendu", "a répondu", "a vendu", "a rompu", "a craint", "a plaint", "a peint", "a éteint", "a atteint", "a conduit", "a construit", "a traduit", "a produit", "a connu", "a paru", "est né", "a plu", "s'est tu", "a pris", "a mis", "a battu", "a lu", "a bu", "a vécu", "a cru", "a ri", "a suivi", "a suffi", "a fait", "a dit", "a écrit", "a reçu", "a déçu", "a aperçu", "a dû", "a peut", "a voulu", "a fallu", "a valu", "s'est assis", "a su", "a vu", "a plu" ];
var nous_passe_compose = [ "avons aimé", "avons arrêté", "avons bavardé", "avons caché", "avons cherché", "avons dansé", "avons donné", "sommes entrés", "avons fermé", "avons grimpé", "avons habité", "avons inventé", "avons joué", "avons lavé", "sommes montés", "avons oublié", "avons parlé", "avons raconté", "avons regardé", "avons salué", "avons sifflé", "avons téléphoné", "avons tiré", "avons volé", "avons commencé", "avons mangé", "avons nagé", "avons lancé", "avons cueilli", "avons ouvert", "avons couvert", "avons offert", "avons souffert", "avons mené", "avons levé", "nous nous sommes levés", "avons jeté", "avons répété", "avons espéré", "avons envoyé", "avons acheté", "avons enlevé", "avons pesé", "avons promené", "nous nous sommes promenés", "avons appelé", "nous nous sommes appelés", "avons épelé", "avons exagéré", "avons inquiété", "avons protégé", "avons séché", "avons ennuyé", "avons nettoyé", "avons essayé", "avons payé", "avons essuyé", "avons applaudi", "avons atterri", "avons choisi", "avons fini", "avons maigri", "avons obéi", "avons puni", "avons rempli", "avons rôti", "avons garanti", "avons grandi", "avons grossi", "avons jauni", "avons réfléchi", "avons réussi", "avons rougi", "avons vieilli", "sommes morts", "avons couru", "sommes venus", "avons tenu", "avons dormi", "sommes partis", "sommes sortis", "avons menti", "avons senti", "avons servi", "avons fui", "nous nous sommes enfuis", "avons attendu", "avons défendu", "sommes descendus", "avons entendu", "avons perdu", "avons rendu", "avons répondu", "avons vendu", "avons rompu", "avons craint", "avons plaint", "avons peint", "avons éteint", "avons atteint", "avons conduit", "avons construit", "avons traduit", "avons produit", "avons connu", "avons paru", "sommes nés", "avons plu", "nous nous sommes tus", "avons pris", "avons mis", "avons battu", "avons lu", "avons bu", "avons vécu", "avons cru", "avons ri", "avons suivi", "avons suffi", "avons fait", "avons dit", "avons écrit", "avons reçu", "avons déçu", "avons aperçu", "avons dû", "avons pu", "avons voulu", "a fallu", "avons valu", "nous sommes assis", "avons su", "avons vu", "a plu" ];
var vous_passe_compose = [ "avez aimé", "avez arrêté", "avez bavardé", "avez caché", "avez cherché", "avez dansé", "avez donné", "êtes entrés", "avez fermé", "avez grimpé", "avez habité", "avez inventé", "avez joué", "avez lavé", "êtes montés", "avez oublié", "avez parlé", "avez raconté", "avez regardé", "avez salué", "avez sifflé", "avez téléphoné", "avez tiré", "avez volé", "avez commencé", "avez mangé", "avez nagé", "avez lancé", "avez cueilli", "avez ouvert", "avez couvert", "avez offert", "avez souffert", "avez mené", "avez levé", "vous vous êtes levés", "avez jeté", "avez répété", "avez espéré", "avez envoyé", "avez acheté", "avez enlevé", "avez pesé", "avez promené", "vous vous êtes promenés", "avez appelé", "vous vous êtes appelés", "avez épelé", "avez exagéré", "avez inquiété", "avez protégé", "avez séché", "avez ennuyé", "avez nettoyé", "avez essayé", "avez payé", "avez essuyé", "avez applaudi", "avez atterri", "avez choisi", "avez fini", "avez maigri", "avez obéi", "avez puni", "avez rempli", "avez rôti", "avez garanti", "avez grandi", "avez grossi", "avez jauni", "avez réfléchi", "avez réussi", "avez rougi", "avez vieilli", "êtes morts", "avez couru", "êtes venus", "avez tenu", "avez dormi", "êtes partis", "êtes sortis", "avez menti", "avez senti", "avez servi", "avez fui", "vous vous êtes enfuis", "avez attendu", "avez défendu", "êtes descendus", "avez entendu", "avez perdu", "avez rendu", "avez répondu", "avez vendu", "avez rompu", "avez craint", "avez plaint", "avez peint", "avez éteint", "avez atteint", "avez conduit", "avez construit", "avez traduit", "avez produit", "avez connu", "avez paru", "êtes nés", "avez plu", "vous vous êtes tus", "avez pris", "avez mis", "avez battu", "avez lu", "avez bu", "avez vécu", "avez cru", "avez ri", "avez suivi", "avez suffi", "avez fait", "avez dit", "avez écrit", "avez reçu", "avez déçu", "avez aperçu", "avez dû", "avez pu", "avez voulu", "a fallu", "avez valu", "vous vous êtes assis", "avez su", "avez vu", "a plu" ];
var ils_passe_compose = [ "ont aimé", "ont arrêté", "ont bavardé", "ont caché", "ont cherché", "ont dansé", "ont donné", "sont entrés", "ont fermé", "ont grimpé", "ont habité", "ont inventé", "ont joué", "ont lavé", "sont montés", "ont oublié", "ont parlé", "ont raconté", "ont regardé", "ont salué", "ont sifflé", "ont téléphoné", "ont tiré", "ont volé", "ont commencé", "ont mangé", "ont nagé", "ont lancé", "ont cueilli", "ont ouvert", "ont couvert", "ont offert", "ont souffert", "ont mené", "ont levé", "se sont levés", "ont jeté", "ont répété", "ont espéré", "ont envoyé", "ont acheté", "ont enlevé", "ont pèsé", "ont promené", "se sont promenés", "ont appelé", "se sont appelés", "ont épelé", "ont exagéré", "ont inquiété", "ont protégé", "ont séché", "ont ennuyé", "ont nettoyé", "ont essayé", "ont payé", "ont essuyé", "ont applaudi", "ont atterri", "ont choisi", "ont fini", "ont maigri", "ont obéi", "ont puni", "ont rempli", "ont rôti", "ont garanti", "ont grandi", "ont grossi", "ont jauni", "ont réfléchi", "ont réussi", "ont rougi", "ont vieilli", "sont morts", "ont couru", "sont venus", "ont tenu", "ont dormi", "sont partis", "sont sortis", "ont menti", "ont senti", "ont servi", "ont fui", "se sont enfuis", "ont attendu", "ont défendu", "sont descendus", "ont entendu", "ont perdu", "ont rendu", "ont répondu", "ont vendu", "ont rompu", "ont craint", "ont plaint", "ont peint", "ont éteint", "ont atteint", "ont conduit", "ont construit", "ont traduit", "ont produit", "ont connu", "ont paru", "sont nés", "ont plu", "se sont tus", "ont pris", "ont mis", "ont battu", "ont lu", "ont bu", "ont vécu", "ont cru", "ont ri", "ont suivi", "ont suffi", "ont fait", "ont dit", "ont écrit", "ont reçu", "ont déçu", "ont aperçu", "ont dû", "ont pu", "ont voulu", "a fallu", "ont valu", "se sont assis", "ont su", "ont vu", "a plu" ];

var je_imparfait = [ "aimais", "arrêtais", "bavardais", "cachais", "cherchais", "dansais", "donnais", "entrais", "fermais", "grimpais", "habitais", "inventais", "jouais", "lavais", "montais", "oubliais", "parlais", "racontais", "regardais", "saluais", "sifflais", "téléphonais", "tirais", "volais", "commençais", "mangeais", "nageais", "lançais", "cueillais", "ouvrais", "couvrais", "offrais", "souffrais", "menais", "levais", "me levais", "jetais", "répétais", "espérais", "envoyais", "achetais", "enlevais", "pesais", "promenais", "me promenais", "appelais", "m'appelais", "épelais", "exagérais", "inquiétais", "protégeais", "séchais", "ennuyais", "nettoyais", "essayais", "payais", "essuyais", "applaudissais", "atterrissais", "choisissais", "finissais", "maigrissais", "obéissais", "punissais", "remplissais", "rôtissais", "garantissais", "grandissais", "grossissais", "jaunissais", "réfléchissais", "réussissais", "rougissais", "vieillissais", "mourais", "courais", "venais", "tenais", "dormais", "partais", "sortais", "mentais", "sentais", "servais", "fuyais", "m'enfuyais", "attendais", "défendais", "descendais", "entendais", "perdais", "rendais", "répondais", "vendais", "rompais", "craignais", "plaignais", "peignais", "éteignais", "atteignais", "conduisais", "construisais", "traduisais", "produisais", "connaissais", "paraissais", "naissais", "plaisais", "me taisais", "prenais", "mettais", "battais", "lisais", "buvais", "vivais", "croyais", "riais", "suivais", "suffisais", "faisais", "disais", "écrivais", "recevais", "décevais", "apercevais", "devais", "pouvais", "voulais", "fallait", "valais", "m'asseyais", "savais", "voyais", "pleuvait" ];
var tu_imparfait = [ "aimais", "arrêtais", "bavardais", "cachais", "cherchais", "dansais", "donnais", "entrais", "fermais", "grimpais", "habitais", "inventais", "jouais", "lavais", "montais", "oubliais", "parlais", "racontais", "regardais", "saluais", "sifflais", "téléphonais", "tirais", "volais", "commençais", "mangeais", "nageais", "lançais", "cueillais", "ouvrais", "couvrais", "offrais", "souffrais", "menais", "levais", "te levais", "jetais", "répétais", "espérais", "envoyais", "achetais", "enlevais", "pesais", "promenais", "te promenais", "appelais", "t'appelais", "épelais", "exagérais", "inquiétais", "protégeais", "séchais", "ennuyais", "nettoyais", "essayais", "payais", "essuyais", "applaudissais", "atterrissais", "choisissais", "finissais", "maigrissais", "obéissais", "punissais", "remplissais", "rôtissais", "garantissais", "grandissais", "grossissais", "jaunissais", "réfléchissais", "réussissais", "rougissais", "vieillissais", "mourais", "courais", "venais", "tenais", "dormais", "partais", "sortais", "mentais", "sentais", "servais", "fuyais", "t'enfuyais", "attendais", "défendais", "descendais", "entendais", "perdais", "rendais", "répondais", "vendais", "rompais", "craignais", "plaignais", "peignais", "éteignais", "atteignais", "conduisais", "construisais", "traduisais", "produisais", "connaissais", "paraissais", "naissais", "plaisais", "te taisais", "prenais", "mettais", "battais", "lisais", "buvais", "vivais", "croyais", "riais", "suivais", "suffisais", "faisais", "disais", "écrivais", "recevais", "décevais", "apercevais", "devais", "pouvais", "voulais", "fallait", "valais", "t'asseyais", "savais", "voyais", "pleuvait" ];
var il_imparfait = [ "aimait", "arrêtait", "bavardait", "cachait", "cherchait", "dansait", "donnait", "entrait", "fermait", "grimpait", "habitait", "inventait", "jouait", "lavait", "montait", "oubliait", "parlait", "racontait", "regardait", "saluait", "sifflait", "téléphonait", "tirait", "volait", "commençait", "mangeait", "nageait", "lançait", "cueillait", "ouvrait", "couvrait", "offrait", "souffrait", "menait", "levait", "se levait", "jetait", "répétait", "espérait", "envoyait", "achetait", "enlevait", "pesait", "promenait", "se promenait", "appelait", "s'appelait", "épelait", "exagérait", "inquiétait", "protégeait", "séchait", "ennuyait", "nettoyait", "essayait", "payait", "essuyait", "applaudissait", "atterrissait", "choisissait", "finissait", "maigrissait", "obéissait", "punissait", "remplissait", "rôtissait", "garantissait", "grandissait", "grossissait", "jaunissait", "réfléchissait", "réussissait", "rougissait", "vieillissait", "mourait", "courait", "venait", "tenait", "dormait", "partait", "sortait", "mentait", "sentait", "servait", "fuyait", "s'enfuyait", "attendait", "défendait", "descendait", "entendait", "perdait", "rendait", "répondait", "vendait", "rompait", "craignait", "plaignait", "peignait", "éteignait", "atteignait", "conduisait", "construisait", "traduisait", "produisait", "connaissait", "paraissait", "naissait", "plaisait", "se taisait", "prenait", "mettait", "battait", "lisait", "buvait", "vivait", "croyait", "riait", "suivait", "suffisait", "faisait", "disait", "écrivait", "recevait", "décevait", "apercevait", "devait", "pouvait", "voulait", "fallait", "valait", "s'asseyait", "savait", "voyait", "pleuvait" ];
var nous_imparfait = [ "aimions", "arrêtions", "bavardions", "cachions", "cherchions", "dansions", "donnions", "entrions", "fermions", "grimpions", "habitions", "inventions", "jouions", "lavions", "montions", "oublions", "parlions", "racontions", "regardions", "saluions", "sifflions", "téléphonions", "tirions", "volions", "commencions", "mangions", "nagions", "lancions", "cueillions", "ouvrions", "couvrions", "offrions", "souffrions", "menions", "levions", "nous levions", "jetions", "répétions", "espérions", "envoyions", "achetions", "enlevions", "pesions", "promenions", "nous promenions", "appelions", "nous appelions", "épelions", "exagérions", "inquiétions", "protégions", "séchions", "ennuyions", "nettoyions", "essayions", "payions", "essuyions", "applaudissions", "atterrissions", "choisissions", "finissions", "maigrissions", "obéissions", "punissions", "remplissions", "rôtissions", "garantissions", "grandissions", "grossissions", "jaunissions", "réfléchissions", "réussissions", "rougissions", "vieillissions", "mourions", "courions", "venions", "tenions", "dormions", "partions", "sortions", "mentions", "sentions", "servions", "fuyions", "nous enfuyions", "attendions", "défendions", "descendions", "entendions", "perdions", "rendions", "répondions", "vendions", "rompions", "craignions", "plaignions", "peignions", "éteignions", "atteignions", "conduisions", "construisions", "traduisions", "produisions", "connaissions", "paraissions", "naissions", "plaisions", "nous taisions", "prenions", "mettions", "battions", "lisions", "buvions", "vivions", "croyions", "riions", "suivions", "suffisions", "faisions", "disions", "écrivions", "recevions", "décevions", "apercevions", "devions", "pouvions", "voulions", "fallait", "valions", "nous asseyions", "savions", "voyions", "pleuvions" ];
var vous_imparfait = [ "aimiez", "arrêtiez", "bavardiez", "cachiez", "cherchiez", "dansiez", "donniez", "entriez", "fermiez", "grimpiez", "habitiez", "inventiez", "jouiez", "laviez", "montiez", "oubliez", "parliez", "racontiez", "regardiez", "saluiez", "siffliez", "téléphoniez", "tiriez", "voliez", "commenciez", "mangiez", "nagiez", "lanciez", "cueilliez", "ouvriez", "couvriez", "offriez", "souffriez", "meniez", "leviez", "vous leviez", "jetiez", "répétiez", "espériez", "envoyiez", "achetiez", "enleviez", "pesiez", "promeniez", "vous promeniez", "appeliez", "vous appeliez", "épeliez", "exagériez", "inquiétiez", "protégiez", "séchiez", "ennuyiez", "nettoyiez", "essayiez", "payiez", "essuyiez", "applaudissiez", "atterrissiez", "choisissiez", "finissiez", "maigrissiez", "obéissiez", "punissiez", "remplissiez", "rôtissiez", "garantissiez", "grandissiez", "grossissiez", "jaunissiez", "réfléchissiez", "réussissiez", "rougissiez", "vieillissiez", "mouriez", "couriez", "veniez", "teniez", "dormiez", "partiez", "sortiez", "mentiez", "sentiez", "serviez", "fuyiez", "vous enfuyiez", "attendiez", "défendiez", "descendiez", "entendiez", "perdiez", "rendiez", "répondiez", "vendiez", "rompiez", "craigniez", "plaigniez", "peigniez", "éteigniez", "atteigniez", "conduisiez", "construisiez", "traduisiez", "produisiez", "connaissiez", "paraissiez", "naissiez", "plaisiez", "vous taisiez", "preniez", "mettiez", "battiez", "lisiez", "buviez", "viviez", "croyiez", "riiez", "suiviez", "suffisiez", "faisiez", "disiez", "écriviez", "receviez", "déceviez", "aperceviez", "deviez", "pouviez", "vouliez", "fallait", "valiez", "vous asseyiez", "saviez", "voyiez", "pleuviez" ];
var ils_imparfait = [ "aimaient", "arrêtaient", "bavardaient", "cachaient", "cherchaient", "dansaient", "donnaient", "entraient", "fermaient", "grimpaient", "habitaient", "inventaient", "jouaient", "lavaient", "montaient", "oubliaient", "parlaient", "racontaient", "regardaient", "saluaient", "sifflaient", "téléphonaient", "tiraient", "volaient", "commençaient", "mangeaient", "nageaient", "lançaient", "cueillaient", "ouvraient", "couvraient", "offraient", "souffraient", "menaient", "levaient", "se levaient", "jetaient", "répétaient", "espéraient", "envoyaient", "achetaient", "enlevaient", "pesaient", "promenaient", "se promenaient", "appelaient", "s'appelaient", "épelaient", "exagéraient", "inquiétaient", "protégeaient", "séchaient", "ennuyaient", "nettoyaient", "essayaient", "payaient", "essuyaient", "applaudissaient", "atterrissaient", "choisissaient", "finissaient", "maigrissaient", "obéissaient", "punissaient", "remplissaient", "rôtissaient", "garantissaient", "grandissaient", "grossissaient", "jaunissaient", "réfléchissaient", "réussissaient", "rougissaient", "vieillissaient", "mouraient", "couraient", "venaient", "tenaient", "dormaient", "partaient", "sortaient", "mentaient", "sentaient", "servaient", "fuyaient", "s'enfuyaient", "attendaient", "défendaient", "descendaient", "entendaient", "perdaient", "rendaient", "répondaient", "vendaient", "rompaient", "craignaient", "plaignaient", "peignaient", "éteignaient", "atteignaient", "conduisaient", "construisaient", "traduisaient", "produisaient", "connaissaient", "paraissaient", "naissaient", "plaisaient", "se taisaient", "prenaient", "mettaient", "battaient", "lisaient", "buvaient", "vivaient", "croyaient", "riaient", "suivaient", "suffisaient", "faisaient", "disaient", "écrivaient", "recevaient", "décevaient", "apercevaient", "devaient", "pouvaient", "voulaient", "fallait", "valaient", "s'asseyaient", "savaient", "voyaient", "pleuvaient" ];

var je_futur = [ "aimerai", "arrêterai", "bavarderai", "cacherai", "chercherai", "danserai", "donnerai", "entrerai", "fermerai", "grimperai", "habiterai", "inventerai", "jouerai", "laverai", "monterai", "oublierai", "parlerai", "raconterai", "regarderai", "saluerai", "sifflerai", "téléphonerai", "tirerai", "volerai", "commencerai", "mangerai", "nagerai", "lancerai", "cueillerai", "ouvrirai", "couvrirai", "offrirai", "souffrirai", "mènerai", "lèverai", "me lèverai", "jetterai", "répéterai", "espérerai", "enverrai", "achèterai", "enlèverai", "pèserai", "promènerai", "me promènerai", "appellerai", "m'appellerai", "épellerai", "exagérerai", "inquiéterai", "protégerai", "sécherai", "ennuierai", "nettoierai", "essaierai", "paierai", "essuierai", "applaudirai", "atterrirai", "choisirai", "finirai", "maigrirai", "obéirai", "punirai", "remplirai", "rôtirai", "garantirai", "grandirai", "grossirai", "jaunirai", "réfléchirai", "réussirai", "rougirai", "vieillirai", "mourrai", "courrai", "viendrai", "tiendrai", "dormirai", "partirai", "sortirai", "mentirai", "sentirai", "servirai", "fuirai", "m'enfuirai", "attendrai", "défendrai", "descendrai", "entendrai", "perdrai", "rendrai", "répondrai", "vendrai", "romprai", "craindrai", "plaindrai", "peindrai", "éteindrai", "atteindrai", "conduirai", "construirai", "traduirai", "produirai", "connaîtrai", "paraîtrai", "naîtrai", "plairai", "me tairai", "prendrai", "mettrai", "battrai", "lirai", "boirai", "vivrai", "croirai", "rirai", "suivrai", "suffirai", "ferai", "dirai", "écrirai", "recevrai", "décevrai", "apercevrai", "devrai", "pourrai", "voudrai", "faudra", "vaudrai", "m'assiérai", "saurai", "verrai", "pleuvra" ];
var tu_futur = [ "aimeras", "arrêteras", "bavarderas", "cacheras", "chercheras", "danseras", "donneras", "entreras", "fermeras", "grimperas", "habiteras", "inventeras", "joueras", "laveras", "monteras", "oublieras", "parleras", "raconteras", "regarderas", "salueras", "siffleras", "téléphoneras", "tireras", "voleras", "commenceras", "mangeras", "nageras", "lanceras", "cueilleras", "ouvriras", "couvriras", "offriras", "souffriras", "mèneras", "lèveras", "te lèveras", "jetteras", "répéteras", "espéreras", "enverras", "achèteras", "enlèveras", "pèseras", "promèneras", "te promèneras", "appelleras", "t'appelleras", "épelleras", "exagéreras", "inquiéteras", "protégeras", "sécheras", "ennuieras", "nettoieras", "essaieras", "paieras", "essuieras", "applaudiras", "atterriras", "choisiras", "finiras", "maigriras", "obéiras", "puniras", "rempliras", "rôtiras", "garantiras", "grandiras", "grossiras", "jauniras", "réfléchiras", "réussiras", "rougiras", "vieilliras", "mourras", "courras", "viendras", "tiendras", "dormiras", "partiras", "sortiras", "mentiras", "sentiras", "serviras", "fuiras", "t'enfuiras", "attendras", "défendras", "descendras", "entendras", "perdras", "rendras", "répondras", "vendras", "rompras", "craindras", "plaindras", "peindras", "éteindras", "atteindras", "conduiras", "construiras", "traduiras", "produiras", "connaîtras", "paraîtras", "naîtras", "plairas", "te tairas", "prendras", "mettras", "battras", "liras", "boiras", "vivras", "croiras", "riras", "suivras", "suffiras", "feras", "diras", "écriras", "recevras", "décevras", "apercevras", "devras", "pourras", "voudras", "faudra", "vaudras", "t'assiéras", "sauras", "verras", "pleuvra" ];
var il_futur = [ "aimera", "arrêtera", "bavardera", "cachera", "cherchera", "dansera", "donnera", "entrera", "fermera", "grimpera", "habitera", "inventera", "jouera", "lavera", "montera", "oubliera", "parlera", "racontera", "regardera", "saluera", "sifflera", "téléphonera", "tirera", "volera", "commencera", "mangera", "nagera", "lancera", "cueillera", "ouvrira", "couvrira", "offrira", "souffrira", "mènera", "lèvera", "se lèvera", "jettera", "répétera", "espérera", "enverra", "achètera", "enlèvera", "pèsera", "promènera", "se promènera", "appellera", "s'appellera", "épellera", "exagérera", "inquiétera", "protégera", "séchera", "ennuiera", "nettoiera", "essaiera", "paiera", "essuiera", "applaudira", "atterrira", "choisira", "finira", "maigrira", "obéira", "punira", "remplira", "rôtira", "garantira", "grandira", "grossira", "jaunira", "réfléchira", "réussira", "rougira", "vieillira", "mourra", "courra", "viendra", "tiendra", "dormira", "partira", "sortira", "mentira", "sentira", "servira", "fuira", "s'enfuira", "attendra", "défendra", "descendra", "entendra", "perdra", "rendra", "répondra", "vendra", "rompra", "craindra", "plaindra", "peindra", "éteindra", "atteindra", "conduira", "construira", "traduira", "produira", "connaîtra", "paraîtra", "naîtra", "plaira", "se taira", "prendra", "mettra", "battra", "lira", "boira", "vivra", "croira", "rira", "suivra", "suffira", "fera", "dira", "écrira", "recevra", "décevra", "apercevra", "devra", "pourra", "voudra", "faudra", "vaudra", "s'assiéra", "saura", "verra", "pleuvra" ];
var nous_futur = [ "aimerons", "arrêterons", "bavarderons", "cacherons", "chercherons", "danserons", "donnerons", "entrerons", "fermerons", "grimperons", "habiterons", "inventerons", "jouerons", "laverons", "monterons", "oublierons", "parlerons", "raconterons", "regarderons", "saluerons", "sifflerons", "téléphonerons", "tirerons", "volerons", "commencerons", "mangerons", "nagerons", "lancerons", "cueillerons", "ouvrirons", "couvrirons", "offrirons", "souffrirons", "mènerons", "lèverons", "nous lèverons", "jetterons", "répéterons", "espérerons", "enverrons", "achèterons", "enlèverons", "pèserons", "promènerons", "nous promènerons", "appellerons", "nous appellerons", "épellerons", "exagérerons", "inquiéterons", "protégerons", "sécherons", "ennuierons", "nettoierons", "essaierons", "paierons", "essuierons", "applaudirons", "atterrirons", "choisirons", "finirons", "maigrirons", "obéirons", "punirons", "remplirons", "rôtirons", "garantirons", "grandirons", "grossirons", "jaunirons", "réfléchirons", "réussirons", "rougirons", "vieillirons", "mourrons", "courrons", "viendrons", "tiendrons", "dormirons", "partirons", "sortirons", "mentirons", "sentirons", "servirons", "fuirons", "nous enfuirons", "attendrons", "défendrons", "descendrons", "entendrons", "perdrons", "rendrons", "répondrons", "vendrons", "romprons", "craindrons", "plaindrons", "peindrons", "éteindrons", "atteindrons", "conduirons", "construirons", "traduirons", "produirons", "connaîtrons", "paraîtrons", "naîtrons", "plairons", "nous tairons", "prendrons", "mettrons", "battrons", "lirons", "boirons", "vivrons", "croirons", "rirons", "suivrons", "suffirons", "ferons", "dirons", "écrirons", "recevrons", "décevrons", "apercevrons", "devrons", "pourrons", "voudrons", "faudra", "vaudrons", "nous assiérons", "saurons", "verrons", "pleuvrons" ];
var vous_futur = [ "aimerez", "arrêterez", "bavarderez", "cacherez", "chercherez", "danserez", "donnerez", "entrerez", "fermerez", "grimperez", "habiterez", "inventerez", "jouerez", "laverez", "monterez", "oublierez", "parlerez", "raconterez", "regarderez", "saluerez", "sifflerez", "téléphonerez", "tirerez", "volerez", "commencerez", "mangerez", "nagerez", "lancerez", "cueillerez", "ouvrirez", "couvrirez", "offrirez", "souffrirez", "mènerez", "lèverez", "vous lèverez", "jetterez", "répéterez", "espérerez", "enverrez", "achèterez", "enlèverez", "pèserez", "promènerez", "vous promènerez", "appellerez", "vous appellerez", "épellerez", "exagérerez", "inquiéterez", "protégerez", "sécherez", "ennuierez", "nettoierez", "essaierez", "paierez", "essuierez", "applaudirez", "atterrirez", "choisirez", "finirez", "maigrirez", "obéirez", "punirez", "remplirez", "rôtirez", "garantirez", "grandirez", "grossirez", "jaunirez", "réfléchirez", "réussirez", "rougirez", "vieillirez", "mourrez", "courrez", "viendrez", "tiendrez", "dormirez", "partirez", "sortirez", "mentirez", "sentirez", "servirez", "fuirez", "vous enfuirez", "attendrez", "défendrez", "descendrez", "entendrez", "perdrez", "rendrez", "répondrez", "vendrez", "romprez", "craindrez", "plaindrez", "peindrez", "éteindrez", "atteindrez", "conduirez", "construirez", "traduirez", "produirez", "connaîtrez", "paraîtrez", "naîtrez", "plairez", "vous tairez", "prendrez", "mettrez", "battrez", "lirez", "boirez", "vivrez", "croirez", "rirez", "suivrez", "suffirez", "ferez", "direz", "écrirez", "recevrez", "décevrez", "apercevrez", "devrez", "pourrez", "voudrez", "faudra", "vaudrez", "vous assiérez", "saurez", "verrez", "pleuvrez" ];
var ils_futur = [ "aimeront", "arrêteront", "bavarderont", "cacheront", "chercheront", "danseront", "donneront", "entreront", "fermeront", "grimperont", "habiteront", "inventeront", "joueront", "laveront", "monteront", "oublieront", "parleront", "raconteront", "regarderont", "salueront", "siffleront", "téléphoneront", "tireront", "voleront", "commenceront", "mangeront", "nageront", "lanceront", "cueilleront", "ouvriront", "couvriront", "offriront", "souffriront", "mèneront", "lèveront", "se lèveront", "jetteront", "répéteront", "espéreront", "enverront", "achèteront", "enlèveront", "pèseront", "promèneront", "se promèneront", "appelleront", "s'appelleront", "épelleront", "exagéreront", "inquiéteront", "protégeront", "sécheront", "ennuieront", "nettoieront", "essaieront", "paieront", "essuieront", "applaudiront", "atterriront", "choisiront", "finiront", "maigriront", "obéiront", "puniront", "rempliront", "rôtiront", "garantiront", "grandiront", "grossiront", "jauniront", "réfléchiront", "réussiront", "rougiront", "vieilliront", "mourront", "courront", "viendront", "tiendront", "dormiront", "partiront", "sortiront", "mentiront", "sentiront", "serviront", "fuiront", "s'enfuiront", "attendront", "défendront", "descendront", "entendront", "perdront", "rendront", "répondront", "vendront", "rompront", "craindront", "plaindront", "peindront", "éteindront", "atteindront", "conduiront", "construiront", "traduiront", "produiront", "connaîtront", "paraîtront", "naîtront", "plairont", "se tairont", "prendront", "mettront", "battront", "liront", "boiront", "vivront", "croiront", "riront", "suivront", "suffiront", "feront", "diront", "écriront", "recevront", "décevront", "apercevront", "devront", "pourront", "voudront", "faudra", "vaudront", "s'assiéront", "sauront", "verront", "pleuvront" ];

var je_plus_que_parfait = [ "avais aimé", "avais arrêté", "avais bavardé", "avais caché", "avais cherché", "avais dansé", "avais donné", "étais entré", "avais fermé", "avais grimpé", "avais habité", "avais inventé", "avais joué", "avais lavé", "étais monté", "avais oublié", "avais parlé", "avais raconté", "avais regardé", "avais salué", "avais sifflé", "avais téléphoné", "avais tiré", "avais volé", "avais commencé", "avais mangé", "avais nagé", "avais lancé", "avais cueilli", "avais ouvert", "avais couvert", "avais offert", "avais souffert", "avais mené", "avais levé", "m'étais levé", "avais jeté", "avais répété", "avais espéré", "avais envoyé", "avais acheté", "avais enlevé", "avais pesé", "avais promené", "m'étais promené", "avais appelé", "m'avais appelé", "avais épelé", "avais exagéré", "avais inquiété", "avais protégé", "avais séché", "avais ennuyé", "avais nettoyé", "avais essayé", "avais payé", "avais essuyé", "avais applaudi", "avais atterri", "avais choisi", "avais fini", "avais maigri", "avais obéi", "avais puni", "avais rempli", "avais rôti", "avais garanti", "avais grandi", "avais grossi", "avais jauni", "avais réfléchi", "avais réussi", "avais rougi", "avais vieilli", "étais mort", "avais couru", "étais venu", "avais tenu", "avais dormi", "étais parti", "étais sorti", "avais menti", "avais senti", "avais servi", "avais fui", "m'étais enfui", "avais attendu", "avais défendu", "étais descendu", "avais entendu", "avais perdu", "avais rendu", "avais répondu", "avais vendu", "avais rompu", "avais craint", "avais plaint", "avais peint", "avais éteint", "avais atteint", "avais conduit", "avais construit", "avais traduit", "avais produit", "avais connu", "avais paru", "étais né", "avais plu", "m'étais tu", "avais pris", "avais mis", "avais battu", "avais lu", "avais bu", "avais vécu", "avais cru", "avais ri", "avais suivi", "avais suffi", "avais fait", "avais dit", "avais écrit", "avais reçu", "avais déçu", "avais aperçu", "avais dû", "avais pu", "avais voulu", "avait fallu", "avais valu", "m'étais assis", "avais su", "avais vu", "avait plu" ];
var tu_plus_que_parfait = [ "avais aimé", "avais arrêté", "avais bavardé", "avais caché", "avais cherché", "avais dansé", "avais donné", "étais entré", "avais fermé", "avais grimpé", "avais habité", "avais inventé", "avais joué", "avais lavé", "étais monté", "avais oublié", "avais parlé", "avais raconté", "avais regardé", "avais salué", "avais sifflé", "avais téléphoné", "avais tiré", "avais volé", "avais commencé", "avais mangé", "avais nagé", "avais lancé", "avais cueilli", "avais ouvert", "avais couvert", "avais offert", "avais souffert", "avais mené", "avais levé", "t'étais levé", "avais jeté", "avais répété", "avais espéré", "avais envoyé", "avais acheté", "avais enlevé", "avais pesé", "avais promené", "t'étais promené", "avais appelé", "t'avais appelé", "avais épelé", "avais exagéré", "avais inquiété", "avais protégé", "avais séché", "avais ennuyé", "avais nettoyé", "avais essayé", "avais payé", "avais essuyé", "avais applaudi", "avais atterri", "avais choisi", "avais fini", "avais maigri", "avais obéi", "avais puni", "avais rempli", "avais rôti", "avais garanti", "avais grandi", "avais grossi", "avais jauni", "avais réfléchi", "avais réussi", "avais rougi", "avais vieilli", "étais mort", "avais couru", "étais venu", "avais tenu", "avais dormi", "étais parti", "étais sorti", "avais menti", "avais senti", "avais servi", "avais fui", "t'étais enfui", "avais attendu", "avais défendu", "étais descendu", "avais entendu", "avais perdu", "avais rendu", "avais répondu", "avais vendu", "avais rompu", "avais craint", "avais plaint", "avais peint", "avais éteint", "avais atteint", "avais conduit", "avais construit", "avais traduit", "avais produit", "avais connu", "avais paru", "étais né", "avais plu", "t'étais tu", "avais pris", "avais mis", "avais battu", "avais lu", "avais bu", "avais vécu", "avais cru", "avais ri", "avais suivi", "avais suffi", "avais fait", "avais dit", "avais écrit", "avais reçu", "avais déçu", "avais aperçu", "avais dû", "avais pu", "avais voulu", "avait fallu", "avais valu", "t'étais assis", "avais su", "avais vu", "avait plu" ];
var il_plus_que_parfait = [ "avait aimé", "avait arrêté", "avait bavardé", "avait caché", "avait cherché", "avait dansé", "avait donné", "était entré", "avait fermé", "avait grimpé", "avait habité", "avait inventé", "avait joué", "avait lavé", "était monté", "avait oublié", "avait parlé", "avait raconté", "avait regardé", "avait salué", "avait sifflé", "avait téléphoné", "avait tiré", "avait volé", "avait commencé", "avait mangé", "avait nagé", "avait lancé", "avait cueilli", "avait ouvert", "avait couvert", "avait offert", "avait souffert", "avait mené", "avait levé", "s'était levé", "avait jeté", "avait répété", "avait espéré", "avait envoyé", "avait acheté", "avait enlevé", "avait pesé", "avait promené", "s'était promené", "avait appelé", "s'était appelé", "avait épelé", "avait exagéré", "avait inquiété", "avait protégé", "avait séché", "avait ennuyé", "avait nettoyé", "avait essayé", "avait payé", "avait essuyé", "avait applaudi", "avait atterri", "avait choisi", "avait fini", "avait maigri", "avait obéi", "avait puni", "avait rempli", "avait rôti", "avait garanti", "avait grandi", "avait grossi", "avait jauni", "avait réfléchi", "avait réussi", "avait rougi", "avait vieilli", "était mort", "avait couru", "était venu", "avait tenu", "avait dormi", "était parti", "était sorti", "avait menti", "avait senti", "avait servi", "avait fui", "s'était enfui", "avait attendu", "avait défendu", "était descendu", "avait entendu", "avait perdu", "avait rendu", "avait répondu", "avait vendu", "avait rompu", "avait craint", "avait plaint", "avait peint", "avait éteint", "avait atteint", "avait conduit", "avait construit", "avait traduit", "avait produit", "avait connu", "avait paru", "était né", "avait plu", "s'était tu", "avait pris", "avait mis", "avait battu", "avait lu", "avait bu", "avait vécu", "avait cru", "avait ri", "avait suivi", "avait suffi", "avait fait", "avait dit", "avait écrit", "avait reçu", "avait déçu", "avait aperçu", "avait dû", "avait pu", "avait voulu", "avait fallu", "avait valu", "s'était assis", "avait su", "avait vu", "avait plu" ];
var nous_plus_que_parfait = [ "avions aimé", "avions arrêté", "avions bavardé", "avions caché", "avions cherché", "avions dansé", "avions donné", "étions entrés", "avions fermé", "avions grimpé", "avions habité", "avions inventé", "avions joué", "avions lavé", "étions montés", "avions oublié", "avions parlé", "avions raconté", "avions regardé", "avions salué", "avions sifflé", "avions téléphoné", "avions tiré", "avions volé", "avions commencé", "avions mangé", "avions nagé", "avions lancé", "avions cueilli", "avions ouvert", "avions couvert", "avions offert", "avions souffert", "avions mené", "avions levé", "nous nous étions levés", "avions jeté", "avions répété", "avions espéré", "avions envoyé", "avions acheté", "avions enlevé", "avions pesé", "avions promené", "nous nous étions promenés", "avions appelé", "nous nous étions appelés", "avions épelé", "avions exagéré", "avions inquiété", "avions protégé", "avions séché", "avions ennuyé", "avions nettoyé", "avions essayé", "avions payé", "avions essuyé", "avions applaudi", "avions atterri", "avions choisi", "avions fini", "avions maigri", "avions obéi", "avions puni", "avions rempli", "avions rôti", "avions garanti", "avions grandi", "avions grossi", "avions jauni", "avions réfléchi", "avions réussi", "avions rougi", "avions vieilli", "étions morts", "avions couru", "étions venus", "avions tenu", "avions dormi", "étions partis", "étions sortis", "avions menti", "avions senti", "avions servi", "avions fui", "nous nous étions enfuis", "avions attendu", "avions défendu", "étions descendus", "avions entendu", "avions perdu", "avions rendu", "avions répondu", "avions vendu", "avions rompu", "avions craint", "avions plaint", "avions peint", "avions éteint", "avions atteint", "avions conduit", "avions construit", "avions traduit", "avions produit", "avions connu", "avions paru", "étions nés", "avions plu", "nous nous étions tus", "avions pris", "avions mis", "avions battu", "avions lu", "avions bu", "avions vécu", "avions cru", "avions ri", "avions suivi", "avions suffi", "avions fait", "avions dit", "avions écrit", "avions reçu", "avions déçu", "avions aperçu", "avions dû", "avions pu", "avions voulu", "avait fallu", "avions valu", "nous nous étions assis", "avions su", "avions vu", "avait plu" ];
var vous_plus_que_parfait = [ "aviez aimé", "aviez arrêté", "aviez bavardé", "aviez caché", "aviez cherché", "aviez dansé", "aviez donné", "étiez entrés", "aviez fermé", "aviez grimpé", "aviez habité", "aviez inventé", "aviez joué", "aviez lavé", "étiez montés", "aviez oublié", "aviez parlé", "aviez raconté", "aviez regardé", "aviez salué", "aviez sifflé", "aviez téléphoné", "aviez tiré", "aviez volé", "aviez commencé", "aviez mangé", "aviez nagé", "aviez lancé", "aviez cueilli", "aviez ouvert", "aviez couvert", "aviez offert", "aviez souffert", "aviez mené", "aviez levé", "vous vous étiez levés", "aviez jeté", "aviez répété", "aviez espéré", "aviez envoyé", "aviez acheté", "aviez enlevé", "aviez pesé", "aviez promené", "vous vous étiez promenés", "aviez appelé", "vous vous étiez appelés", "aviez épelé", "aviez exagéré", "aviez inquiété", "aviez protégé", "aviez séché", "aviez ennuyé", "aviez nettoyé", "aviez essayé", "aviez payé", "aviez essuyé", "aviez applaudi", "aviez atterri", "aviez choisi", "aviez fini", "aviez maigri", "aviez obéi", "aviez puni", "aviez rempli", "aviez rôti", "aviez garanti", "aviez grandi", "aviez grossi", "aviez jauni", "aviez réfléchi", "aviez réussi", "aviez rougi", "aviez vieilli", "étiez morts", "aviez couru", "étiez venus", "aviez tenu", "aviez dormi", "étiez partis", "étiez sortis", "aviez menti", "aviez senti", "aviez servi", "aviez fui", "vous vous étiez enfuis", "aviez attendu", "aviez défendu", "étiez descendus", "aviez entendu", "aviez perdu", "aviez rendu", "aviez répondu", "aviez vendu", "aviez rompu", "aviez craint", "aviez plaint", "aviez peint", "aviez éteint", "aviez atteint", "aviez conduit", "aviez construit", "aviez traduit", "aviez produit", "aviez connu", "aviez paru", "étiez nés", "aviez plu", "vous vous étiez tus", "aviez pris", "aviez mis", "aviez battu", "aviez lu", "aviez bu", "aviez vécu", "aviez cru", "aviez ri", "aviez suivi", "aviez suffi", "aviez fait", "aviez dit", "aviez écrit", "aviez reçu", "aviez déçu", "aviez aperçu", "aviez dû", "aviez pu", "aviez voulu", "avait fallu", "aviez valu", "vous vous étiez assis", "aviez su", "aviez vu", "avait plu" ];
var ils_plus_que_parfait = [ "avaient aimé", "avaient arrêté", "avaient bavardé", "avaient caché", "avaient cherché", "avaient dansé", "avaient donné", "étaient entrés", "avaient fermé", "avaient grimpé", "avaient habité", "avaient inventé", "avaient joué", "avaient lavé", "étaient montés", "avaient oublié", "avaient parlé", "avaient raconté", "avaient regardé", "avaient salué", "avaient sifflé", "avaient téléphoné", "avaient tiré", "avaient volé", "avaient commencé", "avaient mangé", "avaient nagé", "avaient lancé", "avaient cueilli", "avaient ouvert", "avaient couvert", "avaient offert", "avaient souffert", "avaient mené", "avaient levé", "s'étaient levés", "avaient jeté", "avaient répété", "avaient espéré", "avaient envoyé", "avaient acheté", "avaient enlevé", "avaient pesé", "avaient promené", "s'étaient promenés", "avaient appelé", "s'étaient appelés", "avaient épelé", "avaient exagéré", "avaient inquiété", "avaient protégé", "avaient séché", "avaient ennuyé", "avaient nettoyé", "avaient essayé", "avaient payé", "avaient essuyé", "avaient applaudi", "avaient atterri", "avaient choisi", "avaient fini", "avaient maigri", "avaient obéi", "avaient puni", "avaient rempli", "avaient rôti", "avaient garanti", "avaient grandi", "avaient grossi", "avaient jauni", "avaient réfléchi", "avaient réussi", "avaient rougi", "avaient vieilli", "étaient morts", "avaient couru", "étaient venus", "avaient tenu", "avaient dormi", "étaient partis", "étaient sortis", "avaient menti", "avaient senti", "avaient servi", "avaient fui", "s'étaient enfuis", "avaient attendu", "avaient défendu", "étaient descendus", "avaient entendu", "avaient perdu", "avaient rendu", "avaient répondu", "avaient vendu", "avaient rompu", "avaient craint", "avaient plaint", "avaient peint", "avaient éteint", "avaient atteint", "avaient conduit", "avaient construit", "avaient traduit", "avaient produit", "avaient connu", "avaient paru", "étaient nés", "avaient plu", "s'étaient tus", "avaient pris", "avaient mis", "avaient battu", "avaient lu", "avaient bu", "avaient vécu", "avaient cru", "avaient ri", "avaient suivi", "avaient suffi", "avaient fait", "avaient dit", "avaient écrit", "avaient reçu", "avaient déçu", "avaient aperçu", "avaient dû", "avaient pu", "avaient voulu", "avait fallu", "avaient valu", "s'étaient assis", "avaient su", "avaient vu", "avait plu" ];

var je_conditionnel = [ "aimerais", "arrêterais", "bavarderais", "cacherais", "chercherais", "danserais", "donnerais", "entrerais", "fermerais", "grimperais", "habiterais", "inventerais", "jouerais", "laverais", "monterais", "oublierais", "parlerais", "raconterais", "regarderais", "saluerais", "sifflerais", "téléphonerais", "tirerais", "volerais", "commencerais", "mangerais", "nagerais", "lancerais", "cueillerais", "ouvrirais", "couvrirais", "offrirais", "souffrirais", "mènerais", "lèverais", "me lèverais", "jetterais", "répéterais", "espérerais", "enverrais", "achèterais", "enlèverais", "pèserais", "promènerais", "me promènerais", "appellerais", "m'appellerais", "épellerais", "exagérerais", "inquiéterais", "protégerais", "sécherais", "ennuierais", "nettoierais", "essaierais", "paierais", "essuierais", "applaudirais", "atterrirais", "choisirais", "finirais", "maigrirais", "obéirais", "punirais", "remplirais", "rôtirais", "garantirais", "grandirais", "grossirais", "jaunirais", "réfléchirais", "réussirais", "rougirais", "vieillirais", "mourrais", "courrais", "viendrais", "tiendrais", "dormirais", "partirais", "sortirais", "mentirais", "sentirais", "servirais", "fuirais", "m'enfuirais", "attendrais", "défendrais", "descendrais", "entendrais", "perdrais", "rendrais", "répondrais", "vendrais", "romprais", "craindrais", "plaindrais", "peindrais", "éteindrais", "atteindrais", "conduirais", "construirais", "traduirais", "produirais", "connaîtrais", "paraîtrais", "naîtrais", "plairais", "me tairais", "prendrais", "mettrais", "battrais", "lirais", "boirais", "vivrais", "croirais", "rirais", "suivrais", "suffirais", "ferais", "dirais", "écrirais", "recevrais", "décevrais", "apercevrais", "devrais", "pourrais", "voudrais", "faudrait", "vaudrais", "m'assiérais", "saurais", "verrais", "pleuvrait" ];
var tu_conditionnel = [ "aimerais", "arrêterais", "bavarderais", "cacherais", "chercherais", "danserais", "donnerais", "entrerais", "fermerais", "grimperais", "habiterais", "inventerais", "jouerais", "laverais", "monterais", "oublierais", "parlerais", "raconterais", "regarderais", "saluerais", "sifflerais", "téléphonerais", "tirerais", "volerais", "commencerais", "mangerais", "nagerais", "lancerais", "cueillerais", "ouvrirais", "couvrirais", "offriras", "souffrirais", "mèneras", "lèverais", "te lèverais", "jetterais", "répéterais", "espérerais", "enverrais", "achèterais", "enlèverais", "pèserais", "promènerais", "te promènerais", "appellerais", "t'appellerais", "épellerais", "exagérerais", "inquiéterais", "protégerais", "sécherais", "ennuierais", "nettoierais", "essaierais", "paierais", "essuierais", "applaudirais", "atterrirais", "choisirais", "finirais", "maigrirais", "obéirais", "punirais", "remplirais", "rôtirais", "garantirais", "grandirais", "grossirais", "jaunirais", "réfléchirais", "réussirais", "rougirais", "vieillirais", "mourrais", "courrais", "viendrais", "tiendrais", "dormirais", "partirais", "sortirais", "mentirais", "sentirais", "servirais", "fuirais", "t'enfuirais", "attendrais", "défendrais", "descendrais", "entendrais", "perdrais", "rendrais", "répondrais", "vendrais", "romprais", "craindrais", "plaindrais", "peindrais", "éteindrais", "atteindrais", "conduirais", "construirais", "traduirais", "produirais", "connaîtrais", "paraîtrais", "naîtrais", "plairais", "te tairais", "prendrais", "mettrais", "battrais", "lirais", "boirais", "vivrais", "croirais", "rirais", "suivrais", "suffirais", "ferais", "dirais", "écrirais", "recevrais", "décevrais", "apercevrais", "devrais", "pourrais", "voudrais", "faudrait", "vaudrais", "t'assiérais", "sauras", "verrais", "pleuvrait" ];
var il_conditionnel = [ "aimerait", "arrêterait", "bavarderait", "cacherait", "chercherait", "danserait", "donnerait", "entrerait", "fermerait", "grimperait", "habiterait", "inventerait", "jouerait", "laverait", "monterait", "oublierait", "parlerait", "raconterait", "regarderait", "saluerait", "sifflerait", "téléphonerait", "tirerait", "volerait", "commencerait", "mangerait", "nagerait", "lancerait", "cueillerait", "ouvrirait", "couvrirait", "offrirait", "souffrirait", "mènerait", "lèverait", "se lèverait", "jetterait", "répéterait", "espérerait", "enverrait", "achèterait", "enlèverait", "pèserait", "promènerait", "se promènerait", "appellerait", "s'appellerait", "épellerait", "exagérerait", "inquiéterait", "protégerait", "sécherait", "ennuierait", "nettoierait", "essaierait", "paierait", "essuierait", "applaudirait", "atterrirait", "choisirait", "finirait", "maigrirait", "obéirait", "punirait", "remplirait", "rôtirait", "garantirait", "grandirait", "grossirait", "jaunirait", "réfléchirait", "réussirait", "rougirait", "vieillirait", "mourrait", "courrait", "viendrait", "tiendrait", "dormirait", "partirait", "sortirait", "mentirait", "sentirait", "servirait", "fuirait", "s'enfuirait", "attendrait", "défendrait", "descendrait", "entendrait", "perdrait", "rendrait", "répondrait", "vendrait", "romprait", "craindrait", "plaindrait", "peindrait", "éteindrait", "atteindrait", "conduirait", "construirait", "traduirait", "produirait", "connaîtrait", "paraîtrait", "naîtrait", "plairait", "se tairait", "prendrait", "mettrait", "battrait", "lirait", "boirait", "vivrait", "croirait", "rirait", "suivrait", "suffirait", "ferait", "dirait", "écrirait", "recevrait", "décevrait", "apercevrait", "devrait", "pourrait", "voudrait", "faudrait", "vaudrait", "s'assiérait", "saurait", "verrait", "pleuvrait" ];
var nous_conditionnel = [ "aimerions", "arrêterions", "bavarderions", "cacherions", "chercherions", "danserions", "donnerions", "entrerions", "fermerions", "grimperions", "habiterions", "inventerions", "jouerions", "laverions", "monterions", "oublierions", "parlerions", "raconterions", "regarderions", "saluerions", "sifflerions", "téléphonerions", "tirerions", "volerions", "commencerions", "mangerions", "nagerions", "lancerions", "cueillerions", "ouvririons", "couvririons", "offririons", "souffririons", "mènerions", "lèverions", "nous lèverions", "jetterions", "répéterions", "espérerions", "enverrions", "achèterions", "enlèverions", "pèserions", "promènerions", "nous promenerions", "appellerions", "nous appellerions", "épellerions", "exagérerions", "inquiéterions", "protégerions", "sécherions", "ennuierions", "nettoierions", "essaierions", "paierions", "essuierions", "applaudirions", "atterririons", "choisirions", "finirions", "maigririons", "obéirions", "punirions", "remplirions", "rôtirions", "garantirions", "grandirions", "grossirions", "jaunirions", "réfléchirions", "réussirions", "rougirions", "vieillirions", "mourrions", "courrions", "viendrions", "tiendrions", "dormirions", "partirions", "sortirions", "mentirions", "sentirions", "servirions", "fuirions", "nous enfuirions", "attendrions", "défendrions", "descendrions", "entendrions", "perdrions", "rendrions", "répondrions", "vendrions", "romprions", "craindrions", "plaindrions", "peindrions", "éteindrions", "atteindrions", "conduirions", "construirions", "traduirions", "produirions", "connaîtrions", "paraîtrions", "naîtrions", "plairions", "nous tairions", "prendrions", "mettrions", "battrions", "lirions", "boirions", "vivrions", "croirions", "ririons", "suivrions", "suffirions", "ferions", "dirions", "écririons", "recevrions", "décevrions", "apercevrions", "devrions", "pourrions", "voudrions", "faudrait", "vaudrions", "nous assiérions", "saurions", "verrions", "pleuvrions" ];
var vous_conditionnel = [ "aimeriez", "arrêteriez", "bavarderiez", "cacheriez", "chercheriez", "danseriez", "donneriez", "entreriez", "fermeriez", "grimperiez", "habiteriez", "inventeriez", "joueriez", "laveriez", "monteriez", "oublieriez", "parleriez", "raconteriez", "regarderiez", "salueriez", "siffleriez", "téléphoneriez", "tireriez", "voleriez", "commenceriez", "mangeriez", "nageriez", "lanceriez", "cueilleriez", "ouvririez", "couvririez", "offririez", "souffririez", "mèneriez", "lèveriez", "vous lèveriez", "jetteriez", "répéteriez", "espéreriez", "enverriez", "achèteriez", "enlèveriez", "pèseriez", "promèneriez", "vous promeneriez", "appelleriez", "vous appelleriez", "épelleriez", "exagéreriez", "inquiéteriez", "protégeriez", "sécheriez", "ennuieriez", "nettoieriez", "essaieriez", "paieriez", "essuieriez", "applaudiriez", "atterririez", "choisiriez", "finiriez", "maigririez", "obéiriez", "puniriez", "rempliriez", "rôtiriez", "garantiriez", "grandiriez", "grossiriez", "jauniriez", "réfléchiriez", "réussiriez", "rougiriez", "vieilliriez", "mourriez", "courriez", "viendriez", "tiendriez", "dormiriez", "partiriez", "sortiriez", "mentiriez", "sentiriez", "serviriez", "fuiriez", "vous enfuiriez", "attendriez", "défendriez", "descendriez", "entendriez", "perdriez", "rendriez", "répondriez", "vendriez", "rompriez", "craindriez", "plaindriez", "peindriez", "éteindriez", "atteindriez", "conduiriez", "construiriez", "traduiriez", "produiriez", "connaîtriez", "paraîtriez", "naîtriez", "plairiez", "vous tairiez", "prendriez", "mettriez", "battriez", "liriez", "boiriez", "vivriez", "croiriez", "ririez", "suivriez", "suffiriez", "feriez", "diriez", "écririez", "recevriez", "décevriez", "apercevriez", "devriez", "pourriez", "voudriez", "faudrait", "vaudriez", "vous assiériez", "sauriez", "verriez", "pleuvriez" ];
var ils_conditionnel = [ "aimeraient", "arrêteraient", "bavarderaient", "cacheraient", "chercheraient", "danseraient", "donneraient", "entreraient", "fermeraient", "grimperaient", "habiteraient", "inventeraient", "joueraient", "laveraient", "monteraient", "oublieraient", "parleraient", "raconteraient", "regarderaient", "salueraient", "siffleraient", "téléphoneraient", "tireraient", "voleraient", "commenceraient", "mangeraient", "nageraient", "lanceraient", "cueilleraient", "ouvriraient", "couvriraient", "offriraient", "souffriraient", "mèneraient", "lèveraient", "se lèveraient", "jetteraient", "répéteraient", "espéreraient", "enverraient", "achèteraient", "enlèveraient", "pèseraient", "promèneraient", "se promèneraient", "appelleraient", "s'appelleraient", "épelleraient", "exagéreraient", "inquiéteraient", "protégeraient", "sécheraient", "ennuieraient", "nettoieraient", "essaieraient", "paieraient", "essuieraient", "applaudiraient", "atterriraient", "choisiraient", "finiraient", "maigriraient", "obéiraient", "puniraient", "rempliraient", "rôtiraient", "garantiraient", "grandiraient", "grossiraient", "jauniraient", "réfléchiraient", "réussiraient", "rougiraient", "vieilliraient", "mourraient", "courraient", "viendraient", "tiendraient", "dormiraient", "partiraient", "sortiraient", "mentiraient", "sentiraient", "serviraient", "fuiraient", "s'enfuiraient", "attendraient", "défendraient", "descendraient", "entendraient", "perdraient", "rendraient", "répondraient", "vendraient", "rompraient", "craindraient", "plaindraient", "peindraient", "éteindraient", "atteindraient", "conduiraient", "construiraient", "traduiraient", "produiraient", "connaîtraient", "paraîtraient", "naîtraient", "plairaient", "se tairaient", "prendraient", "mettraient", "battraient", "liraient", "boiraient", "vivraient", "croiraient", "riraient", "suivraient", "suffiraient", "feraient", "diraient", "écriraient", "recevraient", "décevraient", "apercevraient", "devraient", "pourraient", "voudraient", "faudrait", "vaudraient", "s'assiéraient", "sauraient", "verraient", "pleuvraient" ];

var je_conditionnel_passe = [ "aurais aimé", "aurais arrêté", "aurais bavardé", "aurais caché", "aurais cherché", "aurais dansé", "aurais donné", "serais entré", "aurais fermé", "aurais grimpé", "aurais habité", "aurais inventé", "aurais joué", "aurais lavé", "serais monté", "aurais oublié", "aurais parlé", "aurais raconté", "aurais regardé", "aurais salué", "aurais sifflé", "aurais téléphoné", "aurais tiré", "aurais volé", "aurais commencé", "aurais mangé", "aurais nagé", "aurais lancé", "aurais cueilli", "aurais ouvert", "aurais couvert", "aurais offert", "aurais souffert", "aurais mené", "aurais levé", "me serais levé", "aurais jeté", "aurais répété", "aurais espéré", "aurais envoyé", "aurais acheté", "aurais enlevé", "aurais pesé", "aurais promené", "me serais promené", "aurais appelé", "m'aurais appelé", "aurais épelé", "aurais exagéré", "aurais inquiété", "aurais protégé", "aurais séché", "aurais ennuyé", "aurais nettoyé", "aurais essayé", "aurais payé", "aurais essuyé", "aurais applaudi", "aurais atterri", "aurais choisi", "aurais fini", "aurais maigri", "aurais obéi", "aurais puni", "aurais rempli", "aurais rôti", "aurais garanti", "aurais grandi", "aurais grossi", "aurais jauni", "aurais réfléchi", "aurais réussi", "aurais rougi", "aurais vieilli", "serais mort", "aurais couru", "serais venu", "aurais tenu", "aurais dormi", "serais parti", "serais sorti", "aurais menti", "aurais senti", "aurais servi", "aurais fui", "me serais enfui", "aurais attendu", "aurais défendu", "serais descendu", "aurais entendu", "aurais perdu", "aurais rendu", "aurais répondu", "aurais vendu", "aurais rompu", "aurais craint", "aurais plaint", "aurais peint", "aurais éteint", "aurais atteint", "aurais conduit", "aurais construit", "aurais traduit", "aurais produit", "aurais connu", "aurais paru", "serais né", "aurais plu", "me serais tu", "aurais pris", "aurais mis", "aurais battu", "aurais lu", "aurais bu", "aurais vécu", "aurais cru", "aurais ri", "aurais suivi", "aurais suffi", "aurais fait", "aurais dit", "aurais écrit", "aurais reçu", "aurais déçu", "aurais aperçu", "aurais dû", "aurais pu", "aurais voulu", "aurait fallu", "aurais valu", "me serais assis", "aurais su", "aurais vu", "aurait plu" ];
var tu_conditionnel_passe = [ "aurais aimé", "aurais arrêté", "aurais bavardé", "aurais caché", "aurais cherché", "aurais dansé", "aurais donné", "serais entré", "aurais fermé", "aurais grimpé", "aurais habité", "aurais inventé", "aurais joué", "aurais lavé", "serais monté", "aurais oublié", "aurais parlé", "aurais raconté", "aurais regardé", "aurais salué", "aurais sifflé", "aurais téléphoné", "aurais tiré", "aurais volé", "aurais commencé", "aurais mangé", "aurais nagé", "aurais lancé", "aurais cueilli", "aurais ouvert", "aurais couvert", "aurais offert", "aurais souffert", "aurais mené", "aurais levé", "t'aurais levé", "aurais jeté", "aurais répété", "aurais espéré", "aurais envoyé", "aurais acheté", "aurais enlevé", "aurais pesé", "aurais promené", "t'aurais promené", "aurais appelé", "t'aurais appelé", "aurais épelé", "aurais exagéré", "aurais inquiété", "aurais protégé", "aurais séché", "aurais ennuyé", "aurais nettoyé", "aurais essayé", "aurais payé", "aurais essuyé", "aurais applaudi", "aurais atterri", "aurais choisi", "aurais fini", "aurais maigri", "aurais obéi", "aurais puni", "aurais rempli", "aurais rôti", "aurais garanti", "aurais grandi", "aurais grossi", "aurais jauni", "aurais réfléchi", "aurais réussi", "aurais rougi", "aurais vieilli", "serais mort", "aurais couru", "serais venu", "aurais tenu", "aurais dormi", "serais parti", "serais sorti", "aurais menti", "aurais senti", "aurais servi", "aurais fui", "t'aurais enfui", "aurais attendu", "aurais défendu", "serais descendu", "aurais entendu", "aurais perdu", "aurais rendu", "aurais répondu", "aurais vendu", "aurais rompu", "aurais craint", "aurais plaint", "aurais peint", "aurais éteint", "aurais atteint", "aurais conduit", "aurais construit", "aurais traduit", "aurais produit", "aurais connu", "aurais paru", "serais né", "aurais plu", "t'aurais tu", "aurais pris", "aurais mis", "aurais battu", "aurais lu", "aurais bu", "aurais vécu", "aurais cru", "aurais ri", "aurais suivi", "aurais suffi", "aurais fait", "aurais dit", "aurais écrit", "aurais reçu", "aurais déçu", "aurais aperçu", "aurais dû", "aurais pu", "aurais voulu", "aurait fallu", "aurais valu", "t'aurais assis", "aurais su", "aurais vu", "aurait plu" ];
var il_conditionnel_passe = [ "aurait aimé", "aurait arrêté", "aurait bavardé", "aurait caché", "aurait cherché", "aurait dansé", "aurait donné", "serait entré", "aurait fermé", "aurait grimpé", "aurait habité", "aurait inventé", "aurait joué", "aurait lavé", "serait monté", "aurait oublié", "aurait parlé", "aurait raconté", "aurait regardé", "aurait salué", "aurait sifflé", "aurait téléphoné", "aurait tiré", "aurait volé", "aurait commencé", "aurait mangé", "aurait nagé", "aurait lancé", "aurait cueilli", "aurait ouvert", "aurait couvert", "aurait offert", "aurait souffert", "aurait mené", "aurait levé", "se serait levé", "aurait jeté", "aurait répété", "aurait espéré", "aurait envoyé", "aurait acheté", "aurait enlevé", "aurait pesé", "aurait promené", "se serait promené", "aurait appelé", "s'aurait appelé", "aurait épelé", "aurait exagéré", "aurait inquiété", "aurait protégé", "aurait séché", "aurait ennuyé", "aurait nettoyé", "aurait essayé", "aurait payé", "aurait essuyé", "aurait applaudi", "aurait atterri", "aurait choisi", "aurait fini", "aurait maigri", "aurait obéi", "aurait puni", "aurait rempli", "aurait rôti", "aurait garanti", "aurait grandi", "aurait grossi", "aurait jauni", "aurait réfléchi", "aurait réussi", "aurait rougi", "aurait vieilli", "serait mort", "aurait couru", "serait venu", "aurait tenu", "aurait dormi", "serait parti", "serait sorti", "aurait menti", "aurait senti", "aurait servi", "aurait fui", "se serait enfui", "aurait attendu", "aurait défendu", "serait descendu", "aurait entendu", "aurait perdu", "aurait rendu", "aurait répondu", "aurait vendu", "aurait rompu", "aurait craint", "aurait plaint", "aurait peint", "aurait éteint", "aurait atteint", "aurait conduit", "aurait construit", "aurait traduit", "aurait produit", "aurait connu", "aurait paru", "serait né", "aurait plu", "se serait tu", "aurait pris", "aurait mis", "aurait battu", "aurait lu", "aurait bu", "aurait vécu", "aurait cru", "aurait ri", "aurait suivi", "aurait suffi", "aurait fait", "aurait dit", "aurait écrit", "aurait reçu", "aurait déçu", "aurait aperçu", "aurait dû", "aurait pu", "aurait voulu", "aurait fallu", "aurait valu", "se serait assis", "aurait su", "aurait vu", "aurait plu" ];
var nous_conditionnel_passe = [ "aurions aimé", "aurions arrêté", "aurions bavardé", "aurions caché", "aurions cherché", "aurions dansé", "aurions donné", "serions entrés", "aurions fermé", "aurions grimpé", "aurions habité", "aurions inventé", "aurions joué", "aurions lavé", "serions montés", "aurions oublié", "aurions parlé", "aurions raconté", "aurions regardé", "aurions salué", "aurions sifflé", "aurions téléphoné", "aurions tiré", "aurions volé", "aurions commencé", "aurions mangé", "aurions nagé", "aurions lancé", "aurions cueilli", "aurions ouvert", "aurions couvert", "aurions offert", "aurions souffert", "aurions mené", "aurions levé", "nous nous serions levés", "aurions jeté", "aurions répété", "aurions espéré", "aurions envoyé", "aurions acheté", "aurions enlevé", "aurions pesé", "aurions promené", "nous nous serions promenés", "aurions appelé", "nous nous serions appelés", "aurions épelé", "aurions exagéré", "aurions inquiété", "aurions protégé", "aurions séché", "aurions ennuyé", "aurions nettoyé", "aurions essayé", "aurions payé", "aurions essuyé", "aurions applaudi", "aurions atterri", "aurions choisi", "aurions fini", "aurions maigri", "aurions obéi", "aurions puni", "aurions rempli", "aurions rôti", "aurions garanti", "aurions grandi", "aurions grossi", "aurions jauni", "aurions réfléchi", "aurions réussi", "aurions rougi", "aurions vieilli", "serions morts", "aurions couru", "serions venus", "aurions tenu", "aurions dormi", "serions partis", "serions sortis", "aurions menti", "aurions senti", "aurions servi", "aurions fui", "nous nous serions enfuis", "aurions attendu", "aurions défendu", "serions descendus", "aurions entendu", "aurions perdu", "aurions rendu", "aurions répondu", "aurions vendu", "aurions rompu", "aurions craint", "aurions plaint", "aurions peint", "aurions éteint", "aurions atteint", "aurions conduit", "aurions construit", "aurions traduit", "aurions produit", "aurions connu", "aurions paru", "serions nés", "aurions plu", "nous nous serions tus", "aurions pris", "aurions mis", "aurions battu", "aurions lu", "aurions bu", "aurions vécu", "aurions cru", "aurions ri", "aurions suivi", "aurions suffi", "aurions fait", "aurions dit", "aurions écrit", "aurions reçu", "aurions déçu", "aurions aperçu", "aurions dû", "aurions pu", "aurions voulu", "aurait fallu", "aurions valu", "nous nous serions assis", "aurions su", "aurions vu", "aurait plu" ];
var vous_conditionnel_passe = [ "auriez aimé", "auriez arrêté", "auriez bavardé", "auriez caché", "auriez cherché", "auriez dansé", "auriez donné", "seriez entrés", "auriez fermé", "auriez grimpé", "auriez habité", "auriez inventé", "auriez joué", "auriez lavé", "seriez montés", "auriez oublié", "auriez parlé", "auriez raconté", "auriez regardé", "auriez salué", "auriez sifflé", "auriez téléphoné", "auriez tiré", "auriez volé", "auriez commencé", "auriez mangé", "auriez nagé", "auriez lancé", "auriez cueilli", "auriez ouvert", "auriez couvert", "auriez offert", "auriez souffert", "auriez mené", "auriez levé", "vous vous seriez levés", "auriez jeté", "auriez répété", "auriez espéré", "auriez envoyé", "auriez acheté", "auriez enlevé", "auriez pesé", "auriez promené", "vous vous seriez promenés", "auriez appelé", "vous vous seriez appelés", "auriez épelé", "auriez exagéré", "auriez inquiété", "auriez protégé", "auriez séché", "auriez ennuyé", "auriez nettoyé", "auriez essayé", "auriez payé", "auriez essuyé", "auriez applaudi", "auriez atterri", "auriez choisi", "auriez fini", "auriez maigri", "auriez obéi", "auriez puni", "auriez rempli", "auriez rôti", "auriez garanti", "auriez grandi", "auriez grossi", "auriez jauni", "auriez réfléchi", "auriez réussi", "auriez rougi", "auriez vieilli", "seriez morts", "auriez couru", "seriez venus", "auriez tenu", "auriez dormi", "seriez partis", "seriez sortis", "auriez menti", "auriez senti", "auriez servi", "auriez fui", "vous vous seriez enfuis", "auriez attendu", "auriez défendu", "seriez descendus", "auriez entendu", "auriez perdu", "auriez rendu", "auriez répondu", "auriez vendu", "auriez rompu", "auriez craint", "auriez plaint", "auriez peint", "auriez éteint", "auriez atteint", "auriez conduit", "auriez construit", "auriez traduit", "auriez produit", "auriez connu", "auriez paru", "seriez nés", "auriez plu", "vous vous seriez tus", "auriez pris", "auriez mis", "auriez battu", "auriez lu", "auriez bu", "auriez vécu", "auriez cru", "auriez ri", "auriez suivi", "auriez suffi", "auriez fait", "auriez dit", "auriez écrit", "auriez reçu", "auriez déçu", "auriez aperçu", "auriez dû", "auriez pu", "auriez voulu", "aurait fallu", "auriez valu", "vous vous seriez assis", "auriez su", "auriez vu", "aurait plu" ];
var ils_conditionnel_passe = [ "auraient aimé","auraient arrêté","auraient bavardé","auraient caché", "auraient cherché", "auraient dansé", "auraient donné", "seraient entrés", "auraient fermé", "auraient grimpé", "auraient habité", "auraient inventé", "auraient joué", "auraient lavé","seraient montés","auraient oublié","auraient parlé","auraient raconté", "auraient regardé", "auraient salué","auraient sifflé","auraient téléphoné","auraient tiré", "auraient volé", "auraient commencé", "auraient mangé", "auraient nagé", "auraient lancé", "auraient cueilli", "auraient ouvert", "auraient couvert", "auraient offert", "auraient souffert", "auraient mené", "auraient levé", "se seraient levés", "auraient jeté", "auraient répété", "auraient espéré", "auraient envoyé", "auraient acheté", "auraient enlevé", "auraient pesé", "auraient promené", "se seraient promenés", "auraient appelé", "se seraient appelés", "auraient épelé", "auraient exagéré", "auraient inquiété", "auraient protégé", "auraient séché", "auraient ennuyé", "auraient nettoyé", "auraient essayé", "auraient payé", "auraient essuyé", "auraient applaudi", "auraient atterri", "auraient choisi", "auraient fini", "auraient maigri", "auraient obéi", "auraient puni", "auraient rempli", "auraient rôti", "auraient garanti", "auraient grandi", "auraient grossi", "auraient jauni", "auraient réfléchi", "auraient réussi", "auraient rougi", "auraient vieilli", "seraient morts", "auraient couru", "seraient venus", "auraient tenu", "auraient dormi", "seraient partis", "seraient sortis", "auraient menti", "auraient senti", "auraient servi", "auraient fui", "se seraient enfuis", "auraient attendu", "auraient défendu", "seraient descendus", "auraient entendu", "auraient perdu", "auraient rendu", "auraient répondu", "auraient vendu", "auraient rompu", "auraient craint", "auraient plaint", "auraient peint", "auraient éteint", "auraient atteint", "auraient conduit", "auraient construit", "auraient traduit", "auraient produit", "auraient connu", "auraient paru", "seraient nés", "auraient plu", "se seraient tus", "auraient pris", "auraient mis", "auraient battu", "auraient lu", "auraient bu", "auraient vécu", "auraient cru", "auraient ri", "auraient suivi", "auraient suffi", "auraient fait", "auraient dit", "auraient écrit", "auraient reçu", "auraient déçu", "auraient aperçu", "auraient dû", "auraient pu", "auraient voulu", "aurait fallu", "auraient valu", "se seraient assis", "auraient su", "auraient vu", "aurait plu" ];

var je_subjonctif = [ "aime", "arrête", "bavarde", "cache", "cherche", "danse", "donne", "entre", "ferme", "grimpe", "habite", "invente", "joue", "lave", "monte", "oublie", "parle", "raconte", "regarde", "salue", "siffle", "téléphone", "tire", "vole", "commence", "mange", "nage", "lance", "cueille", "ouvre", "couvre", "offre", "souffre", "mène", "lève", "me lève", "jette", "répète", "espère", "envoie", "achète", "enlève", "pèse", "promène", "me promène", "appelle", "m'appelle", "épelle", "exagère", "inquiète", "protège", "sèche", "ennuie", "nettoie", "essaie", "paie", "essuie", "applaudisse", "atterrisse", "choisisse", "finisse", "maigrisse", "obéisse", "punisse", "remplisse", "rôtisse", "garantisse", "grandisse", "grossisse", "jaunisse", "réfléchisse", "réussisse", "rougisse", "vieillisse", "meure", "coure", "vienne", "tienne", "dorme", "parte", "sorte", "mente", "sente", "serve", "fuie", "m'enfuie", "attende", "défende", "descende", "entende", "perde", "rende", "réponde", "vende", "rompe", "craigne", "plaigne", "peigne", "éteigne", "atteigne", "conduise", "construise", "traduise", "produise", "connaisse", "paraisse", "naisse", "plaise", "me taise", "prenne", "mette", "batte", "lise", "boive", "vive", "croie", "rie", "suive", "suffise", "fasse", "dise", "écrive", "reçoive", "déçoive", "aperçoive", "doive", "puisse", "veuille", "faille", "vaille", "m'asseye", "sache", "voie", "pleuve" ];
var tu_subjonctif = [ "aimes", "arrêtes", "bavardes", "caches", "cherches", "danses", "donnes", "entres", "fermes", "grimpes", "habites", "inventes", "joues", "laves", "montes", "oublies", "parles", "racontes", "regardes", "salues", "siffles", "téléphones", "tires", "voles", "commences", "manges", "nages", "lances", "cueilles", "ouvres", "couvres", "offres", "souffres", "mènes", "lèves", "te lèves", "jettes", "répètes", "espères", "envoies", "achètes", "enlèves", "pèses", "promènes", "te promènes", "appelles", "t'appelles", "épelles", "exagères", "inquiètes", "protèges", "sèches", "ennuies", "nettoies", "essaies", "paies", "essuies", "applaudisses", "atterrisses", "choisisses", "finisses", "maigrisses", "obéisses", "punisses", "remplisses", "rôtisses", "garantisses", "grandisses", "grossisses", "jaunisses", "réfléchisses", "réussisses", "rougisses", "vieillisses", "meures", "coures", "viennes", "tiennes", "dormes", "partes", "sortes", "mentes", "sentes", "serves", "fuies", "t'enfuies", "attendes", "défendes", "descendes", "entendes", "perdes", "rendes", "répondes", "vendes", "rompes", "craignes", "plaignes", "peignes", "éteignes", "atteignes", "conduise", "construises", "traduises", "produises", "connaisses", "paraisses", "naisses", "plaises", "te taises", "prennes", "mettes", "battes", "lises", "boives", "vives", "croies", "ries", "suives", "suffises", "fasses", "dises", "écrives", "reçoives", "déçoives", "aperçoives", "doives", "puisses", "veuilles", "failles", "vailles", "t'asseyes", "saches", "voies", "pleuves" ];
var il_subjonctif = [ "aime", "arrête", "bavarde", "cache", "cherche", "danse", "donne", "entre", "ferme", "grimpe", "habite", "invente", "joue", "lave", "monte", "oublie", "parle", "raconte", "regarde", "salue", "siffle", "téléphone", "tire", "vole", "commence", "mange", "nage", "lance", "cueille", "ouvre", "couvre", "offre", "souffre", "mène", "lève", "se lève", "jette", "répète", "espère", "envoie", "achète", "enlève", "pèse", "promène", "se promène", "appelle", "s'appelle", "épelle", "exagère", "inquiète", "protège", "sèche", "ennuie", "nettoie", "essaie", "paie", "essuie", "applaudisse", "atterrisse", "choisisse", "finisse", "maigrisse", "obéisse", "punisse", "remplisse", "rôtisse", "garantisse", "grandisse", "grossisse", "jaunisse", "réfléchisse", "réussisse", "rougisse", "vieillisse", "meure", "coure", "vienne", "tienne", "dorme", "parte", "sorte", "mente", "sente", "serve", "fuie", "s'enfuie", "attende", "défende", "descende", "entende", "perde", "rende", "réponde", "vende", "rompe", "craigne", "plaigne", "peigne", "éteigne", "atteigne", "conduise", "construise", "traduise", "produise", "connaisse", "paraisse", "naisse", "plaise", "se taise", "prenne", "mette", "batte", "lise", "boive", "vive", "croie", "rie", "suive", "suffise", "fasse", "dise", "écrive", "reçoive", "déçoive", "aperçoive", "doive", "puisse", "veuille", "faille", "vaille", "s'asseye", "sache", "voie", "pleuve" ];
var nous_subjonctif = [ "aimions", "arrêtions", "bavardions", "cachions", "cherchions", "dansions", "donnions", "entrions", "fermions", "grimpions", "habitions", "inventions", "jouions", "lavions", "montions", "oublions", "parlions", "racontions", "regardions", "saluions", "sifflions", "téléphonions", "tirions", "volions", "commencions", "mangions", "nagions", "lancions", "cueillions", "ouvrions", "couvrions", "offrions", "souffrions", "menions", "levions", "nous levions", "jetions", "répétions", "espérions", "envoyions", "achetions", "enlevions", "pesions", "promenions", "nous promenions", "appelions", "nous appelions", "épelions", "exagérions", "inquiétions", "protégions", "séchions", "ennuyions", "nettoyions", "essayions", "payions", "essuyions", "applaudissions", "atterrissions", "choisissions", "finissions", "maigrissions", "obéissions", "punissions", "remplissions", "rôtissions", "garantissions", "grandissions", "grossissions", "jaunissions", "réfléchissions", "réussissions", "rougissions", "vieillissions", "mourions", "courions", "venions", "tenions", "dormions", "partions", "sortions", "mentions", "sentions", "servions", "fuyions", "nous enfuyions", "attendions", "défendions", "descendions", "entendions", "perdions", "rendions", "répondions", "vendions", "rompions", "craignions", "plaignions", "peignions", "éteignions", "atteignions", "conduisions", "construisions", "traduisions", "produisions", "connaissions", "paraissions", "naissions", "plaisions", "nous taisions", "prenions", "mettions", "battons", "lisions", "buvions", "vivions", "croyions", "riions", "suivions", "suffisions", "fassions", "disions", "écrivions", "recevions", "décevions", "apercevions", "devions", "puissions", "voulions", "faillions", "valions", "nous asseyions", "sachions", "voyions", "pleuvions" ];
var vous_subjonctif = [ "aimiez", "arrêtiez", "bavardiez", "cachiez", "cherchiez", "dansiez", "donniez", "entriez", "fermiez", "grimpiez", "habitiez", "inventiez", "jouiez", "laviez", "montiez", "oubliez", "parliez", "racontiez", "regardiez", "saluiez", "siffliez", "téléphoniez", "tiriez", "voliez", "commenciez", "mangiez", "nagiez", "lanciez", "cueilliez", "ouvriez", "couvriez", "offriez", "souffriez", "meniez", "leviez", "vous leviez", "jetiez", "répétiez", "espériez", "envoyiez", "achetiez", "enleviez", "pesiez", "promeniez", "vous promeniez", "appeliez", "vous appeliez", "épeliez", "exagériez", "inquiétiez", "protégiez", "séchiez", "ennuyiez", "nettoyiez", "essayiez", "payiez", "essuyiez", "applaudissiez", "atterrissiez", "choisissiez", "finissiez", "maigrissiez", "obéissiez", "punissiez", "remplissiez", "rôtissiez", "garantissiez", "grandissiez", "grossissiez", "jaunissiez", "réfléchissiez", "réussissiez", "rougissiez", "vieillissiez", "mouriez", "couriez", "veniez", "teniez", "dormiez", "partiez", "sortiez", "mentiez", "sentiez", "serviez", "fuyiez", "vous enfuyiez", "attendiez", "défendiez", "descendiez", "entendiez", "perdiez", "rendiez", "répondiez", "vendiez", "rompiez", "craigniez", "plaigniez", "peigniez", "éteigniez", "atteigniez", "conduisiez", "construisiez", "traduisiez", "produisiez", "connaissiez", "paraissiez", "naissiez", "plaisiez", "vous taisiez", "preniez", "mettiez", "battiez", "lisiez", "buviez", "viviez", "croyiez", "riiez", "suiviez", "suffisiez", "fassiez", "disiez", "écriviez", "receviez", "déceviez", "aperceviez", "deviez", "puissiez", "vouliez", "failliez", "valiez", "vous asseyiez", "sachiez", "voyiez", "pleuviez" ];
var ils_subjonctif = [ "aiment", "arrêtent", "bavardent", "cachent", "cherchent", "dansent", "donnent", "entrent", "ferment", "grimpent", "habitent", "inventent", "jouent", "lavent", "montent", "oublient", "parlent", "racontent", "regardent", "saluent", "sifflent", "téléphonent", "tirent", "volent", "commencent", "mangent", "nagent", "lancent", "cueillent", "ouvrent", "couvrent", "offrent", "souffrent", "mènent", "lèvent", "se lèvent", "jettent", "répètent", "espèrent", "envoient", "achètent", "enlèvent", "pèsent", "promènent", "se promènent", "appellent", "s'appellent", "épellent", "exagèrent", "inquiètent", "protègent", "sèchent", "ennuient", "nettoient", "essaient", "paient", "essuient", "applaudissent", "atterrissent", "choisissent", "finissent", "maigrissent", "obéissent", "punissent", "remplissent", "rôtissent", "garantissent", "grandissent", "grossissent", "jaunissent", "réfléchissent", "réussissent", "rougissent", "vieillissent", "meurent", "courent", "viennent", "tiennent", "dorment", "partent", "sortent", "mentent", "sentent", "servent", "fuient", "s'enfuient", "attendent", "défendent", "descendent", "entendent", "perdent", "rendent", "répondent", "vendent", "rompent", "craignent", "plaignent", "peignent", "éteignent", "atteignent", "conduisent", "construisent", "traduisent", "produisent", "connaissent", "paraissent", "naissent", "plaisent", "se taisent", "prennent", "mettent", "battent", "lisent", "boivent", "vivent", "croient", "rient", "suivent", "suffisent", "fassent", "disent", "écrivent", "reçoivent", "déçoivent", "aperçoivent", "doivent", "puissent", "veuillent", "faillent", "vaillent", "s'asseyent", "sachent", "voient", "pleuvent" ];

var Französisch = [ "aimer", "arrêter", "bavarder", "cacher", "chercher", "danser", "donner", "entrer", "fermer", "grimper", "habiter", "inventer", "jouer", "laver", "monter", "oublier", "parler", "raconter", "regarder", "saluer", "siffler", "téléphoner", "tirer", "voler", "commencer", "manger", "nager", "lancer", "cueillir", "ouvrir", "couvrir", "offrir", "souffrir", "mener", "lever", "se lever", "jeter", "répéter", "espérer", "envoyer", "acheter", "enlever", "peser", "promener", "se promener", "appeler", "s'appeler", "épeler", "exagérer", "inquiéter", "protéger", "sécher", "ennuyer", "nettoyer", "essayer", "payer", "essuyer", "applaudir", "atterrir", "choisir", "finir", "maigrir", "obéir", "punir", "remplir", "rôtir", "garantir", "grandir", "grossir", "jaunir", "réfléchir", "réussir", "rougir", "vieillir", "mourir", "courir", "venir", "tenir", "dormir", "partir", "sortir", "mentir", "sentir", "servir", "fuir", "s'enfuir", "attendre", "défendre", "descendre", "entendre", "perdre", "rendre", "répondre", "vendre", "rompre", "craindre", "plaindre", "peindre", "éteindre", "atteindre", "conduire", "construire", "traduire", "produire", "connaître", "paraître", "naître", "plaire", "se taire", "prendre", "mettre", "battre", "lire", "boire", "vivre", "croire", "rire", "suivre", "suffire", "faire", "dire", "écrire", "recevoir", "décevoir", "apercevoir", "devoir", "pouvoir", "vouloir", "falloir", "valoir", "s'asseoir", "savoir", "voir", "pleuvoir" ];
var Deutsch = [ "lieben/ mögen", "aufhören/ abstellen", "schwatzen", "verstecken", "suchen", "tanzen", "geben", "eintreten", "schliessen", "klettern", "wohnen", "erfinden", "spielen", "waschen", "steigen", "vergessen", "sprechen", "erzählen", "schauen", "grüssen", "pfeifen", "telefonieren", "ziehen/ schiessen", "stehlen/ fliegen", "anfangen, beginnen",  "essen", "schwimmen", "werfen", "pflücken", "öffnen", "bedecken", "anbieten", "leiden", "führen", "hochheben", "aufstehen", "(weg)werfen", "wiederholen", "hoffen", "schicken", "kaufen", "wegnehmen", "wägen/ wiegen", "spazieren führen", "spazieren", "(an)rufen", "heissen", "buchstabieren", "übertreiben", "beunruhigen, Sorgen machen", "beschützen", "trocknen", "langweilen/ nerven", "reinigen", "versuchen, probieren", "bezahlen", "abtrocknen/ abwischen", "klatschen", "landen", "auswählen", "beenden", "abnehmen (Gewicht)", "gehorchen", "(be-)strafen", "füllen", "braten", "garantieren", "aufwachsen/ älter werden", "zunehmen (Gewicht)", "gelb werden/ gelb färben", "nachdenken", "Erfolg haben/ bestehen", "rot werden", "altern", "sterben", "laufen/ rennen", "kommen", "halten", "schlafen", "abreisen", "ausgehen/ in den Ausgang gehen/ herausgehen", "lügen", "fühlen/ riechen", "bedienen/ nutzen", "fliehen", "davon laufen/ fliehen", "(er-)warten", "verteidigen", "hinuntersteigen", "hören", "verlieren", "zurückgeben", "antworten", "verkaufen", "brechen", "befürchten", "beklagen/ bedauern", "malen", "löschen (Licht)", "erreichen", "führen/ fahren", "bauen", "übersetzen", "ergeben/ erzeugen", "kennen", "scheinen", "geboren werden", "gefallen", "schweigen", "nehmen", "setzen/ stellen/ legen", "schlagen", "lesen", "trinken", "leben", "glauben", "lachen", "folgen", "genügen", "machen", "sagen", "schreiben", "erhalten", "enttäuschen", "erblicken", "müssen", "können", "wollen", "müssen/ notwendig sein", "gelten/ Wert haben", "sich setzen", "wissen", "sehen", "regnen" ];

document.getElementById("Verb").textContent = "Conjuguer";


const zahlen = Array.from({ length: 148 }, (_, i) => i);
let aktuellerSchritt = 0;
let aktuelleZufallsZahl;
let allInputs; 
const fehlerZaehler = {}; 

for (let i = zahlen.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [zahlen[i], zahlen[j]] = [zahlen[j], zahlen[i]];
}

function verbAnzeigen() {
    aktuelleZufallsZahl = zahlen[aktuellerSchritt];
    
    const verbAnzeige = document.getElementById("Verb");
    if (verbAnzeige) {
        verbAnzeige.textContent = Französisch[aktuelleZufallsZahl] + " (" + Deutsch[aktuelleZufallsZahl] + ")";
    }

    for (let key in fehlerZaehler) delete fehlerZaehler[key];

    if (allInputs) {
        allInputs.forEach(input => {
            input.value = "";
            input.disabled = false;
            input.classList.remove('correct-text', 'wrong-border');
            input.style.color = ""; 
        });
    }
}



window.addEventListener('load', () => {

    document.querySelectorAll('.grid-item[id]').forEach(div => {
        const input = div.querySelector('input');
        if (input) {
            input.id = div.id;
            div.removeAttribute('id');
        }
    });

    allInputs = document.querySelectorAll('.verb-input');
    

    verbAnzeigen(); 

    allInputs.forEach(input => {
        input.addEventListener('keydown', function (e) {
            if (e.key === 'Enter') {
                e.preventDefault();

                const listName = this.id; 
                const correctList = window[listName];

                if (!correctList) {
                    console.error("Liste nicht gefunden:", listName);
                    return;
                }

                const solution = correctList[aktuelleZufallsZahl].toLowerCase().trim();
                const userValue = this.value.trim().toLowerCase();


                console.log("---------------------------------------");
                console.log("Feld-ID (Liste):", listName);
                console.log("Verb-Index (0-147):", aktuelleZufallsZahl);
                console.log("ERWARTETE LÖSUNG:", solution);
                console.log("DEINE EINGABE:", userValue);
     

                if (userValue === solution) {

                    this.classList.add('correct-text');
                    this.classList.remove('wrong-border');
                    this.style.color = "#28a745"; 
                    this.disabled = true;
                    delete fehlerZaehler[this.id];

                    const list = Array.from(allInputs);
                    const index = list.indexOf(this);

                    if (list[index + 8]) list[index + 8].focus();
                    if (index >= 40) list[index-39].focus();
                    
                    checkIfAllFinished();
                }  else {

                    fehlerZaehler[this.id] = (fehlerZaehler[this.id] || 0) + 1;
                    console.log("Versuch Nr.:", fehlerZaehler[this.id], "für", listName);

                    if (fehlerZaehler[this.id] >= 3) {

                        this.value = solution; 
                        

                        this.style.color = "#dc3545"; 
                        this.style.fontWeight = "bold"; 
                        
                        this.disabled = true; 
                        this.classList.remove('wrong-border');
                        

                        console.log("%cAutomatisierte Lösung (3 Fehler): " + solution, "color: red;");


                        setTimeout(() => {
                            const list = Array.from(allInputs);
                            const index = list.indexOf(this);
                            if (list[index + 8]) list[index + 8].focus();
                            if (index >= 40) list[index-39].focus();
                            checkIfAllFinished();
                        }, 800);
                    } else {
                      
                        this.classList.add('wrong-border');
                        setTimeout(() => this.classList.remove('wrong-border'), 2000);
                    }
                }
            }
        });
    });
});

function checkIfAllFinished() {
    const alleFertig = Array.from(allInputs).every(input => input.disabled);
    if (alleFertig) {
        setTimeout(() => {
            alert("Exzellent! Nächstes Verb!");
            aktuellerSchritt++;
            if (aktuellerSchritt < zahlen.length) {
                verbAnzeigen();
            } else {
                alert("Du hast alle Verben durch!");
            }
        }, 300);
    }
}

function skip() {

    aktuellerSchritt++;


    if (aktuellerSchritt < zahlen.length) {

        verbAnzeigen();
        

        if (allInputs && allInputs[0]) {
            allInputs[0].focus();
        }
        
        console.log("Verb übersprungen. Neuer Index:", zahlen[aktuellerSchritt]);
    } else {
        alert("Du hast alle Verben der Liste gesehen!");
    }
}

